### ISSUE TITLE
Hide Office 365 Groups from Address List and disable Welcome Message

### ISSUE THREAD

**Issue by amorrowbellarmine** [microsoft/o365-moodle#1086]
#1085 Sorry, I'm not a developer and haven't used github to submit patches to other projects before.
Since early 2018 O365 groups created through Teams are hidden from the Outlook Address List by default. Would it be possible to add this functionality to O365 Groups/Teams created by this plugin?

Could an option also be added to disable the email members receive when they are added to a group? We don't find it helpful for students or faculty to be alerted half a dozen times when the groups are generated at the start of the semester.

Here is a pull request showing a simple change for how to achieve both. I'm not able to find official documentation about the "resourceBehaviorOptions" property, but here are some examples of it being used with the Graph API.
https://techcommunity.microsoft.com/t5/Office-365-Groups/Setting-Unified-Group-properties-via-API/td-p/88101
https://stackoverflow.com/questions/53039373/missing-ad-resourceprovisioningoptions-for-teams-office-365-ad-groups

**Comment by weilai-irl** [comment]
Hi @amorrowbellarmine,

I know it has been a long time since this issue was reported. Sorry for taking that long to process this.

The Microsoft plugins have changed a bit since this was raised. In the current version of the plugin, syncing a course would more likely to result in creating a class Team, rather than creating a group first, then creating a standard Team from the group. The Microsoft Graph API function used to create a (class) Team directly is different from the one used to create a Team:
 - Creating Team uses https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http.
 - Creating group uses https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http.

We have noticed that Teams created directly are hidden from the address list by default, and no welcome emails are sent. It is technically possible to set the "resourceBehaviorOptions" properties in case groups are to be created from courses, but I suppose the value added is more less now, therefore I'd suggest we drop it.

I'm going to close this issue. Please feel free to open it again if needed.

Regards,
Lai

**Comment by bbusschots-mu** [comment]
In our Moodle deployment it is normal for courses to get created before they get lecturers assigned to them, so the way the plugin still works today is that these courses all get groups initially, and then get updated to Teams. This results in thousands of un-wanted welcome emails, and a littered GAL. Please don't down-grade this issue, it remains a very real problem for us, even in 2021!

**Comment by weilai-irl** [comment]
Hi all,

Since 3.9.4 and 3.10.1 release of the plugin in March 2021, groups are created with options "HideGroupInOutlook" and "WelcomeEmailDisabled", which is exactly the requirements in this issue. Please upgrade the plugins to any version later than the named to make sure of the feature.

Regards,
Lai
