### ISSUE TITLE
Programmaticly disconnect moodle from o365 accounts ?

### ISSUE THREAD

**Issue by chriskincaid24** [microsoft/o365-moodle#1087]
Is there a method to programatically disconnect a moodle user from office 365 user? I am trying to automate our name change processes and hit a snag with moodle authentications. I tried inserting a record into the mdl_local_o365_matchqueue table with openidconnect set to 0, but get "Moodle user is already connected to Office 365." error when the cron job runs.

**Comment by jamesmcq** [comment]
Hi @chriskincaid24 - best I can do is point you to the user control panel file (/local/o365/classes/page/ucp.php), specifically methods "mode_disconnecttoken" and "mode_disconnectlogin". These are the methods called when a user disconnects using the user interface.

**Comment by HadynM-TWoA** [comment]
Hi, was just going to request an enhancement for this too.  We currently disconnect the user through the management interface, then when the user logs in again it creates a connection.  My thoughts are that if the token table, mdl_auth_oidc_token, stored and used the user id rather than, or as well as, the username it may make it more robust.  This is similar to how it uses the AAD user GUID in the oidcuniqid field but has the oidcusername field (which doesn't appear to ever update).  Thoughts?

**Comment by jamesmcq** [comment]
@HadynM-TWoA The auth_oidc_token table now uses the user ID - thanks! On a side note, I'm closing this issue as it seems to be resolved. If there are any other questions please open a new issue. Thanks!
