### ISSUE TITLE
Delta sync not seeing users added to security group

### ISSUE THREAD

**Issue by cbrherms** [microsoft/o365-moodle#1114]
We use a security group to dictate who should be synced with moodle, but it would appear that a delta sync is not picking up new users when "User Creation restriction" is set to Office 365 group membership.

A user has been added to the security group and multiple reruns of a delta usersync is run, output is as follows each time:

```
...... Starting sync
...... No skiptoken (delta) stored.
...... Using deltatoken.
...... Using delta sync.
...... Contacting Azure AD...
...... Got response from Azure AD
...... Storing deltatoken
...... Clearing skiptoken (delta) (none received)
...... No users received to sync.
...... Sync process finished.
```

It is noted that the newly added user to group is not picked up and created in Moodle. 

Running Moodle 3.7 and local_o365 3.6.0.0

**Comment by jamesmcq** [comment]
@cbrherms I've heard from a few people that group membership is not a change that triggers a user being reported to us in delta sync. That may be a change needed in the Graph API rather than something we can do in the plugins. Can you confirm whether delta sync is working for you for other user data? (i.e. change a user's first/last name and see if they come up in delta sync?)

**Comment by jamesmcq** [comment]
Closing this as it looks like group membership is not something that trigger delta sync. Unfortunately this is not something we can change on our end. A full sync should pick this up, so you may want to look at staying on full-sync if you have frequent group membership changes.
