### ISSUE TITLE
Recreating a deleted office 365 group does not recreate a team

### ISSUE THREAD

**Issue by Rossco88** [microsoft/o365-moodle#1137]
We have an issue were during testing a team and office 365 group were deleted directly in our tenant. When running the recreate office 365 group through maintenance tools, the group is created but not the team. When trying to create a team we cannot link it back to that group

**Comment by jamesmcq** [comment]
Hi @Rossco88, yes the recreate teams maintenance tool does not currently include the Team. I've added this to our list of future improvements.

**Comment by gusfersa** [comment]
Hi, I've the same issue. Recreate groups at maintenance tools, but only recreate outlook group. I've to create Teams Group on Admin Portal, on Groups section

**Comment by weilai-irl** [comment]
Hi @Rossco88, @gusfersa,

I know this is a long shot, we have some updates for you.

Recreating a deleted group still doesn't create the Team, however, in the 3.9.4 and 3.10.1 release made available in March 2021 (at the time of writing this), we have added a new feature to allow site admins to manage course connections to Teams. The feature is in the "Advanced" tab of the configuration page, in item "Manage Team Connections". On this page, if a course is connected to a Group only, but a Team has been created from the group (regardless how the Team was created), site admins can connect the course to the Team linked to the group. This may fit your particular use case.

I understand that this is different from recreating the Team with creating the group, but at least it would achieve the same.

Please give it a try and let us know if the original request in this issue is still needed. 

Regards,
Lai

**Comment by Rossco88** [comment]
Thanks Lai

I shall work with the team to get the latest version of the plugin with our modifications working and test this feature

Thanks
