### ISSUE TITLE
Teams/Group creation failing due to naming conventions

### ISSUE THREAD

**Issue by upats** [microsoft/o365-moodle#1141]
Hello, my institution is interested in auto-provisioning Microsoft Teams for courses using the Office 365 plugin. In testing, we are seeing the creation fail because the names of courses do not meet the naming conventions our O365 admin has put in place:

`
Could not create group for course #17423. Reason: Error in API call: The property is missing a required prefix/suffix per your organization's Group naming requirements.`

If possible, it would be helpful to add a way in the app to define a prefix/suffix to add to Groups that are auto-created via the Moodle plugin.

**Comment by jamesmcq** [comment]
Thanks @upats - I've added this to our future features list.

**Comment by shteevy** [comment]
Hello, is there any update for this feature into the Moodle plugin ? Thanks, Steve

**Comment by weilai-irl** [comment]
Hi all,

Sorry for the delay in processing this.

The workflow of creating Teams/groups has evolved since the original reporting of the issue. For a bit of background, I'll explain the current process as of November 2020.

If synchronisation is enabled for a course, on groupcreate task run:
 - Moodle will check if the course has an enrolled user that could be set as the owner of the Team (determined by the "local/o365:teamowner" capability check on the course), and would create a class Team (a Team using the education template) if one if found.
 - If no suitable owner is found, the task will try to create a group first, and on subsequent groupcreate task runs, it will check for suitable owners, and if one is found, it will try to create a group from the Team. Notably, Teams created from groups cannot have custom templates, so they will always be standard Teams rather than class Teams.

Different Microsoft Graph API functions are used to create Teams and groups, and they behave differently to group naming policy:
 - Creating class Teams directly uses [create team function](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&tabs=http), and group naming policy isn't considered, i.e. creating a Team with name not matching the policy will succeed.
 - Creating a group uses [create group function](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-beta&tabs=http), and group naming policy is applied, i.e. creating a group with name not matching the policy will fail.


The following enhancements are on our map, and will be included in the upcoming releases in the near future:
 - Option for site admins to decide if there's a need to fall back to create groups instead of Teams in case a suitable Team owner cannot be find in a course.
 - Option for site admins to define a naming convention for the Team, e.g. allow defining prefix, suffix, and choose between course full name or short name for the main part.

I believe the second feature described will solve the original issue reported in this one.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @upats, @shteevy,

To give you an update - the feature to allow site admins to configure Team / group naming conventions were introduced in release 3.9.3 and 3.10.0 in January 2021. This should solve the issue.

Please note that as mentioned in my previous note, if the course is configured to sync to Teams (instead of group only), the Team's name will not need to comply with group naming policy.

Please upgrade to the latest version of the plugins and try it out.

I'll close this issue for now. If you have any questions about the same issue, feel free to re-open, or create a new issue.

Regards,
Lai
