### ISSUE TITLE
Do not replace standard Moodle theme

### ISSUE THREAD

**Issue by StevenC365** [microsoft/o365-moodle#1148]
Our client has invested in tailoring the Moodle theme to suit their institution, however the Moodle Tab in Teams replaces this with O365_Boost. Please provide an option to retain the client theme.

**Comment by kkiiskin** [comment]
Hi

is there progress on this?

What does the o365_boost theme actually provide? Normal boost-based client theme seems to work fine within Teams apps, although we havent tested it thoroughly.

**Comment by nenorojas** [comment]
@weilai-irl also, https://aka.ms/TeamsMoodle link in https://moodle.org/plugins/theme_boost_o365teams is broken.

**Comment by nenorojas** [comment]
@kkiiskin @StevenC365 we have updated the description of the theme: 

The purpose of the Teams theme is to display a custom view of the Moodle course home page within Teams. The Office 365 Moodle plugin dynamically enables this theme only when users access their Moodle courses within Teams, while keeping the selected Moodle theme when users access their Moodle sites on the web browser. For more details, go to https://docs.moodle.org/38/en/Office365

Moodle sites using Teams feature of Office 365 integration should have this theme installed, but should NOT set this theme as the site default theme. When a course page is opened in Microsoft Teams, this theme will be automatically applied within Teams only for the session. The theme aims at giving users a unified experience in Microsoft Teams.

Features of the theme includes:

    Removed blocks.
    Removed navigation.
    Removed header and footer.
    Microsoft Team UI elements.
    Adapt to Microsoft Teams theme changes (default, dark, and high contrast).

You don't need to use this theme, the impact will only be in how the courses will show in the tab, not in Moodle. And we cannot adjust this theme to get your custom theme settings because the purpose was to show Moodle course content with same look and feel of Microsoft Teams application.
