### ISSUE TITLE
Create a sharing link (or updated permissions) for files shared from OneDrive for Business and SharePoint

### ISSUE THREAD

**Issue by zckb** [Microsoft/o365-moodle#115]
Microsoft Graph supports sharable links and file permissions within an organization for OneDrive for Business and SharePoint Online. 

http://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_createlink
http://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/permission_get
http://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/permission_update

When a file from OneDrive for Business or SharePoint is added via repository plugin, a shareable link and/or file permissions should be created/updated for recipients of the file.

**Comment by vinhub** [comment]
Some more details on this after further discussion: 
When someone selects a OneDrive file in the file picker and selects "Create an alias/shortcut to the file" we need to create a sharing link instead of a normal link. At present, since we are creating just a normal link, if teachers don't set permissions appropriately, students may not be able to access the file. We should create a sharing link (readonly, shared within the org) using the item_createlink api.

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/133

Note that the API for creating sharing link is available only in the unified API so this type of link is only created when unified API is in effect.

**Comment by petersercombe** [comment]
Is this issue resolved now?
