### ISSUE TITLE
Error in API call: Team owner not found

### ISSUE THREAD

**Issue by grant007** [microsoft/o365-moodle#1150]
When our Moodle cron runs I receive a long string of errors like the one below. In Office 365 many Groups/Teams are missing (not created). Please advise on what may be the root cause and how I may remedy or troubleshoot further.

Syncing to group "a1a94897-2c79-40f5-ad28-c71433456910"
Could not create team for course #51. Reason: Error in API call: Team owner not found for a1a94897-2c79-40f5-ad28-c71433456910.

**Comment by MustafaOzman** [comment]
Cron job can't find the lecturer ID which linked with Office 365.
I was facing this issue before and fixed by matching the teacher (owner)for this group in Moodle with office 365 then the issue will be solved. teacher must login to office 365 from Moodle then you can run the cron job for creating groups.

**Comment by weilai-irl** [comment]
Hi @grant007,

You saw this error because creating a Team requires at least one owner. A team owner is essentially a teacher in the Moodle course, who needs to be an office365 user, i.e. using auth_oidc thus cannot be a manual authenticate user.

When a course is configured to be synced but no teacher is found, it will create a group in Azure AD instead - a group doesn't need an owner. In subsequent scheduled task runs, Moodle will try to create a Team from the group, but it won't be successful until an office365 user enrolled to the course has teacher role. You will see an error like this for attempts for each course Moodle tries to create Teams.

We have plan to optimise this - doing a check if see if a teacher exists before attempting to create team from group. When implemented, it should remove all issues like this. We expect it to be in the next release or the one after.

Regards,
Lai

**Comment by weilai-irl** [comment]
@grant007 
Request is put in #1204.
