### ISSUE TITLE
System API user does not necessarily need to be an admin

### ISSUE THREAD

**Issue by gormster** [microsoft/o365-moodle#1179]
Currently, setting the System API user includes a prompt for admin consent. This means that AAD will simply throw up an error if you try to log in with any non-admin user account.

However, this is not necessary. Admin consent must be given to the application, but this can be done separately with the *Provide Admin Consent* button on the settings page. I've patched this by simply removing the `$extraparams = ['prompt' => 'admin_consent'];` from `\local_o365\page\acp::mode_setsystemuser` (and deleting the parameter from the call to `initiateauthrequest`). User sync still works just fine; I've not tested other features yet as the purpose of my testing was to find the most restrictive set of permissions that would allow user sync to still function properly. However, nothing is obviously broken yet.

Is there a good reason admin consent is prompted when signing in as the System API user?

**Comment by jamesmcq** [comment]
@gormster We require admin consent for the system API user because there are features within the plugins that use the system API user to perform admin-level operations, or which assume a non-restricted access environment. For some setups or use cases that don't need these functions, I'd recommend using application access instead of the system API user, and setting permissions as you see fit. The system API user is mostly still present for legacy or specialty purposes at this point anyway, and application access is much preferred. 

Please note though that our testing and development assumes the permissions we list in the documentation so we can't guarantee full operation on different sets of permissions - please test your preferred permissions selections thoroughly before going to production.
