### ISSUE TITLE
Feature request local/o365: Option to match azure usernames to moodle emails, instead of moodle usernames

### ISSUE THREAD

**Issue by kristian-94** [microsoft/o365-moodle#1188]
Azure usernames are set as an email address in our particular system. This means it won't match the moodle username, but it will match the email address. 

This change would be a new option in the User Sync settings page. 

> Match Azure usernames to moodle emails instead of moodle usernames during the sync

> Enabling this option will match azure usernames to moodle emails, instead of the default behaviour which is azure usernames to moodle usernames.

**Comment by kristian-94** [comment]
I've completed this in the two latest commits here: https://github.com/catalyst/o365-moodle/commits/wr321931-MOODLE_37_STABLE

Not sure why it's not letting me do a pull request though, it says they have entirely different commit histories when I try to make it.

**Comment by avegys** [comment]
Hi Kristian,

Thank you for your efforts helping to improve Office365 plugins. Your code changes implementing new feature has been included into latest release for Moodle 3.7 and Moodle 3.8.

Bets regards,
Andrius

**Comment by parsival7** [comment]
I'm trying to integrate moodle 3.9.1+ with office 365 (250 000 user accounts)
I have to use the options:
"Match Azure usernames to moodle emails instead of moodle usernames during the sync"

but when I run cron, nothing happens: 
-
Execute scheduled task: Synchronizuj użytkowników z usługą Azure AD. (local_o365\task\usersync)
... started 13:52:13. Current memory use 8.6MB.
...... Starting sync
...... No skiptoken (delta) stored.
...... Using deltatoken.
...... Using delta sync.
...... Contacting Azure AD...
...... Got response from Azure AD
...... Storing deltatoken
...... Clearing skiptoken (delta) (none received)
...... No users received to sync.
...... Sync process finished.
... used 8 dbqueries
... used 0.79387903213501 seconds
Scheduled task complete: Synchronize your users with Azure AD. (local_o365\task\usersync)
Execute scheduled task: Create user groups in Office&nbsp;365 (local_o365\task\groupcreate)
... started 13:52:13. Current memory use 8.8MB.
Groups not enabled, skipping...
... used 0 dbqueries
... used 0.00019598007202148 seconds
Scheduled task complete: Create user groups in the package Office&nbsp;365 (local_o365\task\groupcreate)
Execute scheduled task: Process Match Queue (local_o365\task\processmatchqueue)
... started 13:52:13. Current memory use 8.8MB.
... used 1 dbqueries
... used 0.0045931339263916 seconds
Scheduled task complete: Process Match Queue (local_o365\task\processmatchqueue)
Execute scheduled task: Background processing for cleaning up question statistics caches (core\task\question_stats_cleanup_task)
... started 13:52:13. Current memory use 9.1MB.
-
When I try to log in to moodle, it is possible only for accounts  with email as username.
