### ISSUE TITLE
OIDC-authentication breaks Guest login 

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#1201]
Hi 
When new user is logging in to Moodle for the first time with OIDC authentication, they can in some circumstances break the guest user. 
This happens when the users doesn't already have a Moodle account and it is supposed to be created while logging in.

Steps to recreate:
1) Log in to o365 in the same browser 
2) Log in to Moodle as guest ('Login in as Guest' in the login-page) 
3) Go back to loginpage for ('Log in' -link in the upper right corner) 
4) Log in to Moodle using OpenID Connect

After that guest-login doesn't work normally anymore, because it has been changed to oidc-auth and password changed to 'not cached'. Also there are corresponding rows in the auth_oidc_token and local_o365_objects tables.

You can fix things in the database, but this should not happen in the first place.

**Comment by kkiiskin** [comment]
I see that this is fixed to 3.7 -branch. Is the fix coming to other branches or don't you support them anymore?

**Comment by weilai-irl** [comment]
Hi @kkiiskin ,

Our plan going forward would be to only support 3.7 and 3.8 (which will be released in the coming weeks).

Regards,
Lai

**Comment by kkiiskin** [comment]
Hi

I think it would be reasonable to support Moodle's LTS versions - 3.5 at the moment - until their support is ended. For 3.5 it ends 10 May 2021.

Many don't update to every version of Moodle that are released and instead use the LTS-version.

**Comment by nenorojas** [comment]
Hi @kkiiskin ,

We do support Moodle 3.5 but we are using Moodle release calendar as our guide:  https://docs.moodle.org/dev/Releases#Moodle_3.5_.28LTS.29

Which means that we are only releasing security fixes for this version:

Bug fixes for general core bugs in 3.5.x ended May 2019 (12 months).
Bug fixes for security issues in 3.5.x will end 10 May 2021 (36 months).

Bug fixes for 3.6 also ended, so that's why we are releasing only for 3.7 that is covered at this moment:

Bug fixes for general core bugs in 3.7.x will end 11 May 2020 (12 months).

And of course, it will be fixed for 3.8 when the new versions are upgraded, this is work in progress. 

Cheers
