### ISSUE TITLE
Repository 'alias' doesn't work as expected

### ISSUE THREAD

**Issue by hamboneZA** [microsoft/o365-moodle#1220]
There are essentially 3 ways of adding a file to moodle in _most_ 3rd party repositories. 

However the behavior of the Office 365 repository is not consistent with other repositories. The ways one can add a file from, for example, Dropbox is as follows:

### Typical behavior

1. Make a copy of the file
As expected the file is copied from Dropbox into moodle so it is available locally and the connection to the file in Dropbox is broken. This works as expected on the O365 repository.

2. Link to the file directly
This option will take one out of moodle to Dropbox, perhaps in a popup window, so the person needing the file has to login to Dropbox to see the file. This works as expected on the O365 repository.

3. Create an alias/shortcut to the file
This is where O365 is inconsistent with other 3rd party repositories. The idea behind the 'alias' option is that the file is added to moodle so it is available locally, then moodle periodically checks to see if the file has changed and if it has download a new copy. 

This way file permissions can be set using Moodle rather than the 3rd party authenticating the user.

The O365 alias option doesn't work like that - instead it behaves like option 2. by sending the person to Office365 where they would need to login.

### Next steps?
Is this count as a feature request or is this the expected behavior of the Office365 repository.
Plugin Version: 3.7.0 (02019052000) }Moodle Version:  3.7.1+ (20190718)

**Comment by nenorojas** [comment]
Hi @hamboneZA ,

We will review this case, I've noticed that this documentation created in 2016 https://docs.moodle.org/38/en/repository_office365 for this repository was mentioning the possibility of "Create an alias/shortcut to the file". So at some stage that was dropped or stopped working. 

Regards

**Comment by hamboneZA** [comment]
@nenorojas stoked this is getting some attention per #1320. Game changer for us if we can alias files / embed from filepicker for things like Stream of Teams meetings and docs that are updated in SP regularly. Thanks for the good work you do for this community.

**Comment by nenorojas** [comment]
Hi @hamboneZA  

Can you please test with latest version of the plugin on a Moodle 3.9?

The Office 365 repository should show now the option to create an alias.

![image](https://user-images.githubusercontent.com/3680797/95999596-f31ccc00-0e2d-11eb-913d-441c954683fa.png)

Regards

**Comment by mwehr** [comment]
Hi @nenorojas

I would like to test the "Alias" feature but I could not find the proposed feature in the Moodle_39_Stable branch.
Is there any special branch with this feature?

regards
Mario

**Comment by discosilvia** [comment]
Hi, jumping in here because we have the same issue.
The option you @nenorojas previewed is visible in our environment, but this is what a student (not logged in to OneDrive for Business) gets, even though public link sharing is enabled on Microsoft's side.

![image](https://user-images.githubusercontent.com/3822806/108710029-c7b09900-7513-11eb-8120-79cb94073bf1.png)

Thx for looking in to this!

**Comment by hamboneZA** [comment]
Finally I've a production 3.9 so i can give you a proper answer. This functionality is working as I expect. A file in SharePoint must be shared with the Moodle user who is redirected and SSO to OneDrive / the course's SharePoint. IMO you can close this. I suspect that @discosilvia's issue is unrelated to the repo plugin, I could be wrong though. @nenorojas

**Comment by nenorojas** [comment]
Hi @discosilvia

This is a different issue, when you use the option "Create an alias/shortcut to the file." the link added is the same as sharing only to users of the same Microsoft tenant where file is located:

![image](https://user-images.githubusercontent.com/3680797/114735157-d01b9800-9d3c-11eb-9aaf-b268ec77e49f.png)

If you want to place in Moodle a file available available to everybody on the web, I'd recommend to get the link directly in Onedrive and add to an activity manually instead of using the repository_o365 plugin. 

Regards

Oswaldo
