### ISSUE TITLE
o365 Sync Settings bug

### ISSUE THREAD

**Issue by ssllqq** [microsoft/o365-moodle#1253]
First selected parameter of sync settings will not be executed.

    public static function get_sync_options() {
        $aadsync = get_config('local_o365', 'aadsync');
        $aadsync = array_flip(explode(',', $aadsync));
        return $aadsync;
    }

It will return:
`$aadsync = array('nodelta' => 0)`

next function who use this array:
  
	public static function sync_option_enabled($option) {
        $options = static::get_sync_options();
        return (!empty($options[$option])) ? true : false;
    }

PHP documentation https://www.php.net/manual/en/function.empty.php

Empty of `($options['nodelta'] => 0)` will return `true`, which means first selected parameter
 are `!true = false` and will not be executed.

**Comment by avegys** [comment]
Hi Tomas,

Thank you for noticing this. The fix will be released soon.

Best regards,
Andrius

**Comment by ssllqq** [comment]
Hi

I see you fixed it, but don't forget this setting can make mess in system or make some problems after sync cron execution, so you need remove first selected setting from config and inform administrators about this change.

**Comment by avegys** [comment]
Hi Tomas,

Thank you for your concern. However, the function with this bug is only used with 'nodelta' and 'delete' settings. This means we should only be concerned when the first setting selected is one of them. It would be wrong to remove first selected setting from config for all instances.
We will take into consideration to add aadsync setting checking before releasing new plugin version.

Thank you,
Andrius

**Comment by avegys** [comment]
Hi Tomas,

Thank you for helping to improve local_o365 plugin. A new version of plugin has been released for Moodle 3.7 and Moodle 3.8. This version includes the fix to your mentioned issue.

Best regards,
Andrius
