### ISSUE TITLE
unit test failure: test_sync_users_delete

### ISSUE THREAD

**Issue by kristian-94** [microsoft/o365-moodle#1260]
> 1) local_o365_usersync_testcase::test_sync_users_delete
> Failed asserting that '0' matches expected 1.
> 
> /var/www/site/local/o365/tests/usersync_test.php:391
> /var/www/site/lib/phpunit/classes/advanced_testcase.php:80
> 
> To re-run:
>  vendor/bin/phpunit "local_o365_usersync_testcase" local/o365/tests/usersync_test.php

I found that this is caused by this commit, and removing the if statement here: https://github.com/microsoft/moodle-local_o365/commit/b1809710da8b28c40e0c48826a2fa98dde75708a#diff-4b072bc3ef15c6cb1c32ba2ac5870719L726

Looks like we moved this functionality out of `\local_o365\feature\usersync\main` and into the scheduled task. But the unit test doesn't run the task, just the usersync sync_users method. 

I think it should be moved back into the usersync class so it can be more easily called in unit tests.

**Comment by weilai-irl** [comment]
Hi @kristian-94,

I confirm the move of the user suspension/deletion function out of old sync_users() into a new function suspend_users() is intentional. The root reason is that sync_users() function can only process users passed into that function, which can be either the full list of users, or delta. However, the updated suspending/deleting users function require full list of users to work. The logic to check if the list of users is full/delta is out of the scope of the sync_users() function, therefore the move.

You are right that this makes unittest of the user deletion feature more complicated. I have temporarily removed the tests for the user deletion out of the unittest, and will eye at adding them back in to the new functions in the near future.

Regards,
Lai

**Comment by weilai-irl** [comment]
The latest release contains the changes mentioned in the last note.
Issue closed.
