### ISSUE TITLE
New and existing users in Moodle is not synching from Azure AD

### ISSUE THREAD

**Issue by PrasanthRaguraman** [microsoft/o365-moodle#1261]
Hi All,

I have created a user in Azure AD and ran the Synch users with Azure AD in Moodle. The new user is not created in Moodle and I cannot see the user in the log file. Moreover not all users from Azure AD are getting synched with Moodle even after running the batch process for more than 7 times.

Thank you for your help. Please find attached the log file from the batch process in Moodle and the steps I did to replicate the issue.
[local_o365_task_usersync-17.log](https://github.com/microsoft/o365-moodle/files/4662554/local_o365_task_usersync-17.log)
[replication.docx](https://github.com/microsoft/o365-moodle/files/4662568/replication.docx)

**Comment by avegys** [comment]
Hi Prasanth,

Please check your local_o365 plugin settings 'Sync settings' tab and check usersynccreationrestriction setting. You have set some rules there and your new users do not match them. This is why your users are not created.

Best regards,
Andrius

**Comment by PrasanthRaguraman** [comment]
![image](https://user-images.githubusercontent.com/65717587/82568371-c1118180-9b8f-11ea-9cbd-fe2c2f8ae5f4.png)

I have checked the 'Synch Settings'  tab for usersynccreationrestriction setting its blank.

**Comment by avegys** [comment]
Hi Prasanth,

Could you check what Moodle version are you using? What is the version number of your used local_o365 plugin?

Best regards,
Andrius

**Comment by PrasanthRaguraman** [comment]
Hi,
I have checked the Moodle version - 3.7.3+ and for local_0365 am not able to get the version number from the portal. However, I have downloaded the latest 0365 plugins from the moodle directory.

**Comment by avegys** [comment]
Hi Prasanth,

Do you still have sync issue?
It is strange that your log shows messages "Cannot create user because they do not meet the configured user creation restriction" which is available only when the restriction setting is set. Maybe log is from older times when regular expression was set.
Anyway, it is hard to tell exactly why your user was not synced and I can not see anything else in logs. My guess would be that maybe you have a lot of users in Azure and you have set to do full sync each time the scheduled task runs. In such case you were hitting 100 users limit. It looks from logs that exactly 100 users were returned. This means you never reach other users.

I suggest to disable full sync each time for now as delta sync does not have limitations like full sync has. Other option would be to wait till limitation removal for full sync will be released #1279 (this should happen next week).

Best regards,
Andrius

**Comment by avegys** [comment]
Hi Prasanth,

The limitation removal is now released in the latest release. Please update your plugin and the issue should be gone.

Best regards,
Andrius
