### ISSUE TITLE
Object ID Field not Mapping Correctly (appearing to be empty)

### ISSUE THREAD

**Issue by bbusschots-mu** [microsoft/o365-moodle#1307]
Using the latest Moodle 3.5 LTS release with the most recent version of the plugin for Moodle 3.5 I have configured the following custom field:

<img width="752" alt="Screenshot 2020-07-03 at 11 07 06" src="https://user-images.githubusercontent.com/4949446/86458972-0348e980-bd1e-11ea-8d5e-655b8c6490c0.png">

With that field created, I then added the following mapping:

<img width="753" alt="Screenshot 2020-07-03 at 11 07 44" src="https://user-images.githubusercontent.com/4949446/86459006-122f9c00-bd1e-11ea-8da4-1eea1656d650.png">

When a user is created via the sync task the field is blank. I don not believe it should be possible for an object not to have an ID in AAD, so I assume this is a bug?

**Comment by nenorojas** [comment]
Hi @bbusschots-mu ,

We are only releasing bug fixes for currently supported versions of Moodle https://docs.moodle.org/dev/Releases#Version_support.

A new round of releases is scheduled to be released by the end of this week for Moodle 3.7 (last bug fixes release), 3.8 and new version of plugins for Moodle 3.9. After the new version is released, can you please re-test in a newer Moodle version with the latest version of plugins installed and let us know if the bug is still happening?

Regards

**Comment by nenorojas** [comment]
Hi @bbusschots-mu ,

I just confirmed that this bug is still available on latest version and we will work on that for next release. 

Regards

**Comment by weilai-irl** [comment]
@bbusschots-mu 
Hi Bart,

We have fixed this issue in the latest release 3.9.3 for Moodle 3.9, and 3.10.0 for Moodle 3.10. I'll mark this issue closed for now.

We can talk separately regarding how you plan to have this applied to your site.

Regards,
Lai
