### ISSUE TITLE
usersync scheduled task can't sync users with numeric username

### ISSUE THREAD

**Issue by weilai-irl** [microsoft/o365-moodle#1338]
We found an issue where when "Match preexisting Moodle users with same-named accounts in Azure AD" option is enabled, and a lot of existing unmatched users have numbers as username, the task would be unable to map users.

We have found a solution to this issue, and will include it in the next release.

**Comment by shaunt-nait** [comment]
Hi I have an issue with the Match preexisting users. Here's the output of the error.

Execute scheduled task: Sync users with Azure AD. (local_o365\task\usersync)
...... Starting sync
...... No skiptoken (delta) stored.
...... No deltatoken stored.
...... Using delta sync.
...... Contacting Azure AD...
...... Got response from Azure AD
...... Storing deltatoken
...... Clearing skiptoken (delta) (none received)
...... 135820 users received. Syncing...
... used 11 dbqueries
... used 398.97954082489 seconds
Scheduled task failed: Sync users with Azure AD. (local_o365\task\usersync),Error reading from database (number of parameters must be between 0 and 65535

I'm trying to match users as a lot of our users haven't logged in since our change to oidc and are not being added to the MS Teams. Any assistance would be greatly appreciated.

**Comment by weilai-irl** [comment]
Hi @shaunt-nait ,

If you haven't done so, please report the error you are having in a separate issue entry, as it may probably caused by a different reason.

Regards,
Lai

**Comment by weilai-irl** [comment]
The issue reported in this one has been fixed in the latest release.
