### ISSUE TITLE
Moodle courses AND users not syncing to Teams

### ISSUE THREAD

**Issue by plastro** [microsoft/o365-moodle#1341]
Hi, 
I thought it would be a good summer job, to bring our corona-lock-down-helpers teams and moodle together.
All steps implementing the conneciton were successfull.

Now trying to start the sync process I have got no synced users and no synced groups.

Our environment
Windows Server 2019 AD Server
Moodle 3.9.1 with the newest plugins

_We are using LDAP to login to our moodle-server - so all our users are using SSO with our AD - we have only LDAP-synced users in moodle. no direct system users.
Can this be the problem?_

**Our SyncSettings**
local_o365 | aadsync:
only option 3, 4 and 7
- delete previously synced accounts..,.
- match preexisting moodle users with same-named accounts in azureAd
- sync office 365 profile photos...

**Output for task "\local_o365\task\usersync":**
Deprecated: Directive 'track_errors' is deprecated in Unknown on line 0
Execute scheduled task: Synchronisieren Sie Benutzer mit Azure AD. (local_o365\task\usersync)
... started 16:23:17. Current memory use 3MB.
...... Starting sync
...... No skiptoken (delta) stored.
...... Using deltatoken.
...... Using delta sync.
...... Contacting Azure AD...
...... Got response from Azure AD
...... Storing deltatoken
...... Clearing skiptoken (delta) (none received)
...... No users received to sync.
...... Checking deleted users list...
...... Sync process finished.
... used 5 dbqueries
... used 1.019721031189 seconds
Scheduled task complete: Synchronisieren Sie Benutzer mit Azure AD. (local_o365\task\usersync)

**Output for task "\local_o365\task\groupcreate"**
Deprecated: Directive 'track_errors' is deprecated in Unknown on line 0
Execute scheduled task: Nutzergruppen in Office 365 erstellen (local_o365\task\groupcreate)
... started 16:24:48. Current memory use 3MB.
No groups waiting to have class notebook created.
All courses have a group recorded.
Attempting to create team for course #89...
Skip creating team for course #89. Reason: No owner
Attempting to create team for course #498...
Skip creating team for course #498. Reason: No owner
Attempting to create team for course #525...
Skip creating team for course #525. Reason: No owner
Attempting to create team for course #630...
Skip creating team for course #630. Reason: No owner
... used 58 dbqueries
... used 0.09017014503479 seconds
Scheduled task complete: Nutzergruppen in Office 365 erstellen (local_o365\task\groupcreate)

KR
Markus

**Comment by weilai-irl** [comment]
Hi @plastro,

For the issue in user sync, I see "No users received to sync." in the output. It basically means usersync task doesn't think there's any user left to be synced. I noticed that you are using delta sync, which can be the reason. Try to perform a full sync first (one of the options is to perform a full sync on each run), and see what you can see in the output. Delta sync would only sync users that have been updated since the last sync.

You also mentioned that your existing users are using auth_ldap. You may want to consider what you want to do with the existing users. There are generally three approaches:
 - convert authentication type of the existing users to auth_oidc, which can be done either using a custom script, or using the user sync option "Switch matched users to Office 365 (OpenID Connect) authentication".
 - keep existing users using auth_ldap, and set up connections either by not checking "Switch matched users to Office 365 (OpenID Connect) authentication" option, or by manually set up connections using the "Manage User Connections" link in the "advanced" tab.

For the issue with course sync, the error message is self explanatory. In order for a team to be created from a course, it is a requirement for the course to have an enrolled user who can act as team owner, because teams always require at least one owner. This is documented at https://docs.moodle.org/310/en/Office365#Teams_vs_Group.

Regards,
Lai
