### ISSUE TITLE
Members on teams not syncing with enrolments on Moodle

### ISSUE THREAD

**Issue by Randomix** [microsoft/o365-moodle#1344]
Hi,

After having turned on the Microsoft teams creation for 1 specific course I am finding that the enrollments between Moodle and the O365 group are not being processed.

When the group was first created the members were added correctly based on the users that were enrolled on the Moodle course  at that time. But now as I enroll more users (Students and Teachers) onto the same Moodle course they are not always synced.

Un-enrolling users from the Moodle course also seems to not remove them from the Teams group (even when left for a few days).

We're using Application access as the connection method for the 365 integration.

I have tried running 'Resync users in groups for courses' from the maintenance tab but with no success as 0 users are found to add or remove.

I'd appreciate it if someone could provide some help with this issue. Please let me know if you need any further information.

The only error received in the last 24 hours is;

local_o365\oauth2\token::instance local_o365\feature\sds\task\sync::get_apiclient:364: Cannot retrieve a token for the base resource. Data: (null)

However we are not using SDS.

![image](https://user-images.githubusercontent.com/1078746/90004924-5eabb700-dc8e-11ea-9054-7b4c31c5ff56.png)

**Version Information**
Moodle version 3.8.4+ (20200723)
Microsoft block 3.8.0.3 (2020020303)
OpenID Connect 3.8.0.3 (2020020303)
Microsoft Office 365 Integration 3.8.0.3 (2020020303)

**Comment by Randomix** [comment]
Update:

The users that I removed from the Moodle course yesterday morning have now been removed from the Teams group.

Is there a reason why this would have taken 26+ hours?

**Comment by tristdac** [comment]
I don't see which function is syncing the Moodle participants with the Teams participants apart from "resync_group_membership". But that looks like its only called in the initial Team creation function/task and by manually running "Resync users in groups for courses" maintenace script as you've done. 

Is a teams Owners and members static after the initial creation? Course and group enrolment in schools/colleges/unis isn't static and teachers don't always have the luxury of waiting until their class enrolments have been fully completed and stable before creating teams.

I've got a feeling when you ran the maintenance script, it did the job. I've noticed a huge refresh delay within Teams membership. If you check membership from the Teams admin console, you see instant changes that sometimes take many hours/days to be reflected in the app/Web app. Sometimes signing out, closing the app and logging in forces a refresh.

**Comment by weilai-irl** [comment]
Hi @Randomix,

There is normally a delay between when Moodle calls Microsoft Graph API functions to make team owner/member changes, and when those changes can be seen in teams. In our experience this is normally in the matter of minutes. I have never seen a delay of over 1 hour.

After the initial sync of a course, team owner/member sync is triggered by Moodle observer functions listening for enrolment updated events and role assignment change events, and they are not triggered from cronjobs. It's worth mentioning that these calls in observer functions are triggered only once, i.e. there is no mechanism to monitor if the calls fails, and retry.

With that in mind, because you eventually saw the team membership changes taking place after some time, it's safe to assume that the calls to Microsoft Graph API were successful, and it was genuinely the delay on the Microsoft side causing the issue.

I'll therefore close this issue.

Regards,
Lai
