### ISSUE TITLE
Moodle 3.9 to 3.9.1+ disables openid

### ISSUE THREAD

**Issue by diddiminn** [microsoft/o365-moodle#1347]
I have zero understanding in code and this forum is probably not the right place, but I'm sure you'll point me in right direction as I've seen there is a lot of very nice people on github 👍 

Every time I try to upgrade moodle from 3.9 to 3.9.1+ then after the upgrade, I can't login using openid, 

If I manually try to browse the openid link https://moodle.******.**/auth/oidc/

I get:

Argument 1 passed to core\session\manager::login_user() must be an instance of stdClass, bool given, called in [dirroot]/lib/moodlelib.php on line 4672

Before the update I make sure all plugins are updated so I'm lost... :)

**Comment by weilai-irl** [comment]
Hi @diddiminn,

The most likely cause of the issue is username of the Moodle user doesn't match the username claim from the login token Moodle receives from Office 365. To verify that, you can go to the "Microsoft Office 365 Integration" configuration page in the "site administration" section, go to "advanced" tab, and go to "View maintenance tools" link in the "Tools" section. From the page, click the "Cleanup OpenID Connect Tokens" link. The page will show you all users with username mismatches

Unfortunately, the link will not automatically fix the the mismatches. You will need to go to the database, and delete the records with mismatched usernames from mdl_auth_oidc_token table yourself. After it, the login should work.

Regards,
Lai
