### ISSUE TITLE
Moodle to Teams courses synchronization limit

### ISSUE THREAD

**Issue by bayaopriol** [microsoft/o365-moodle#1348]
Hi, Does anyone have experience with moodle to teams course synchronization? 
I tried to sync 200 courses into teams. When cron starts, 5 courses are synchronized and then stops. The next time cron starts, it will also only sync 5 courses to teams. Why does the plugin only sync 5 courses each time?

I want to sync more than 10,000 courses into teams. 

(Moodle 3.9.1 with Microsoft Office 365 Integration 3.9.0 - 2020071500)

Regards,
Bayao

**Comment by weilai-irl** [comment]
Hi @bayaopriol,

Each groupcreate task (which creates teams) is limited to create at most 5 teams for performance considerations. This is a hardcoded limitation, and cannot be changed from settings.

If you want to remove this limitation, you can change line 119 of local/o365/classes/feature/usergroups/coursegroups.php from
`$courses = $this->DB->get_recordset_sql($sql, $params, 0, 5);`
to
`$courses = $this->DB->get_recordset_sql($sql, $params, 0);`

The change above will sync all course at once, which will take very long time and probably time out if you try to run on over 10,000 courses. So maybe change 5 to something higher, like 100, and maybe gradually to higher value if it can finish.

Regards,
Lai

**Comment by bayaopriol** [comment]
Hi @weilai-irl ,

Thank you very much!!! This is very good news!

Regards,
Bayao

**Comment by weilai-irl** [comment]
New feature request in this one is to allow site admins to control how many courses to sync in each groupcreate task run.

**Comment by flipmode45** [comment]
Ive been struggling for a week to work out why new courses are not syncing to Teams - they don't appear in the logs at all. In a last ditch effort, I've unselected every course from sync except the 14 new courses. As I type, the new courses are now syncing to Teams.   I can't help but notice that before I unticked all the existing courses, the number of queries in the log always showed around 203, which is remarkably similar to the limit referred to above. 

Is it possible that some kind of flag is not getting set/reset so that the next set of courses waiting to be synced happen on the next cycle?

**Comment by flipmode45** [comment]
> Ive been struggling for a week to work out why new courses are not syncing to Teams - they don't appear in the logs at all. In a last ditch effort, I've unselected every course from sync except the 14 new courses. As I type, the new courses are now syncing to Teams. I can't help but notice that before I unticked all the existing courses, the number of queries in the log always showed around 203, which is remarkably similar to the limit referred to above.
> 
> Is it possible that some kind of flag is not getting set/reset so that the next set of courses waiting to be synced happen on the next cycle?

Ok, I think I figured it out. If there are 5 Teams showing in error the log, the 5 Teams prevent any future Teams from being synced. See log:

Could not create group for course #271. Reason: Error in API call: Invalid value specified for property 'mailNickname' of resource 'Group'.
Syncing group membership for course #271
Could not find group object ID in local_o365_objects for course 271. Please ensure group exists first.
Could not create group for course #273. Reason: Error in API call: Invalid value specified for property 'mailNickname' of resource 'Group'.
Syncing group membership for course #273
Could not find group object ID in local_o365_objects for course 273. Please ensure group exists first.
Could not create group for course #275. Reason: Error in API call: Invalid value specified for property 'mailNickname' of resource 'Group'.
Syncing group membership for course #275
Could not find group object ID in local_o365_objects for course 275. Please ensure group exists first.
Could not create group for course #292. Reason: Error in API call: Invalid value specified for property 'mailNickname' of resource 'Group'.
Syncing group membership for course #292
Could not find group object ID in local_o365_objects for course 292. Please ensure group exists first.
Could not create group for course #293. Reason: Error in API call: Invalid value specified for property 'mailNickname' of resource 'Group'.
Syncing group membership for course #293
Could not find group object ID in local_o365_objects for course 293. Please ensure group exists first.
Processed courses: 5

**Comment by weilai-irl** [comment]
Hi all,

@bayaopriol, the latest release 3.9.4 and 3.10.1 introduced a new setting "Courses to sync per task run" in the "Sync Settings" tab of the "Microsoft 365 Integration" configuration page to allow site admins control how many courses to sync in each task run. Please upgrade to this version and try it out. I'll close this issue for now, but feel free to reopen it if the new setting doesn't do what you expect it to do.

@flipmode45, the issue you are having is different from the one reported in this github issue. The error message explains it well - Invalid value specified for property 'mailNickname' of resource 'Group'. Either there are invalid characters in the mailNickname property of the group to be created, or the group mailNickname doesn't comply with your graph name policy, or group with the same mailNickname already exists. Since 3.9.3 and 3.10.0 release of the plugins, you can configure prefix and suffix of the mailNickname of groups to avoid duplicates with existing groups as well. Please give it try. If you still have questions, please open a new issue in github.

Regards,
Lai
