### ISSUE TITLE
O365 repository - jpg,png,etc alias/shortcut not visible

### ISSUE THREAD

**Issue by bayaopriol** [microsoft/o365-moodle#1355]
Hi @weilai-irl 

Could you help me again?

"Create an alias/shortcut to the file" from OneDrive, or Teams group works well for a ppt,doc,etc. document, but does not appear for images (png,jpg..) What could be the reason?

Moodle 3.9.1+ (Build: 20200807) + repository_office365 3.9.0 2020071500

![picturenotvisible](https://user-images.githubusercontent.com/69870341/91657720-72934d80-eac3-11ea-9092-a62ed21f3520.jpg)

![rep_pictures](https://user-images.githubusercontent.com/69870341/91657799-4fb56900-eac4-11ea-8011-fd08639be8cb.jpg)

![reposnv](https://user-images.githubusercontent.com/69870341/91669227-a26a4180-eb13-11ea-9319-8a8684f74a35.jpg)

Regards,
Bayao

**Comment by weilai-irl** [comment]
Hi @bayaopriol,

Sorry for not getting back to you sooner.

After some investigation, @chrisoconnor found out that the root of the issue is "Cross-Origin Read Blocking (CORB) blocked cross-origin response". When an image is to be added using either "Link to the file directly" or "Create a an alias/shortcut to the file" option, the image will not be copied from OneDrive to Moodle data folder, rather it either adds an <img> tag with src linking directly to the file in OneDrive, or adds an <img> tag with src linking to an URL in Moodle but redirecting to the the file in OneDrive. Either way, this will end up with an <img> tag with src in OneDrive.

If you try to copy the URL and open it in a new browser tab, the image would display correctly; however, when trying to display the image on a Moodle page, the cross-origin read blocking feature would block it. See https://www.chromium.org/Home/chromium-security/corb-for-developers for details of the feature.

I don't think there's a technical solution to it. Effectively this means that image embedding using either "Link to the file directly" or "Create a an alias/shortcut to the file" option won't work. We will look at removing the options for images.

Regards,
Lai

**Comment by chrisoconnor** [comment]
Hi @bayaopriol,
I have looked at this issue and there is no way fix this issue, without changing core Moodle and the file manager.
