### ISSUE TITLE
Users not syncing

### ISSUE THREAD

**Issue by shaunt-nait** [microsoft/o365-moodle#1358]
Hi I've added oidc and o365 to my 3.8 Moodle site. I've enabled custom groups as we have thousands of courses and don't want to enabled them all. When I enable a course the users that are listed that have logged in via oidc are added without issues. Since oidc is new some users haven't logged in a the type the team is enabled and don't sync. Is there anyway to sync these users? I see some have recently logged in within the last 24 hours and are still not being sync'd to teams. 

I have the \local_o365\task\groupcreate task running every 2 minutes. Any assistance would be greatly appreciated.

**Comment by darius-m** [comment]
If I understand correctly, we may have had a similar issue, that was solved by running a full user sync (not an incremental one). That forces the system to fetch all users, regardless of when they were last synced, and update their information.

**Comment by weilai-irl** [comment]
Hi @shaunt-nait,

I don't know if I fully understand the issue, but I'll try to explain how group/team member sync works, and hopefully this will explain the behaviour you saw. We can then look at how this can be improved to work in your case.

When a course is initially synced, it will look for all existing enrolled users, and add them to the group/team, and give them either owner or member role whereas appropriate. After this initial sync, it will only respond to user enrolment and role assignment changes **on users in auth_oidc auth type**, i.e.
 - when a auth_oidc user is enrolled to a course, she will be added to the team/group.
 - when a auth_oidc user who had student role in the course is given teacher role, she will be made owner of the team/group from member. (this is actually controlled by capability check, "student" and "teacher" role are used for example)
 - when a auth_oidc user is unenrolled from the course, she will be removed from the team/group.

The possible problem here is, if the auth type of a user is changed from other types to auth_oidc, then it will not automatically perform group/team membership actions on existing courses, i.e. it will not try to add the user to the teams/groups that the user should be in. A such user can only be added to a team/group the next time her enrolment status or enrol assignment status gets changed, and this needs to happen on each course.

With this in mind, could you confirm if your issue would have been caused by this?

If this is the issue, there are a few possible technical solutions to it:
1. Add an observer function that listens to user updated event, and if the updated field is auth type (need to find out if the log contains such details), then resync all team/group memberships for the user. Performance may be a problem for this approach; also some user updated function may not trigger events, thus may be missed in this.
2. Add an administration tool to resync team/group memberships for all users in bulk.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @shaunt-nait,

Could you confirm if this is still an issue please.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi all,

I'll close the issue due to inactivity. Feel free to re-open it if this is still required.

Regards,
Lai
