### ISSUE TITLE
 AADSTS700016: Application with identifier 'x' was not found in the directory 'y'.

### ISSUE THREAD

**Issue by coriordan** [microsoft/o365-moodle#1382]
We've recently deployed the Office 365 plugin and we've been inundated with errors from users with the following signature:

Request Id: c222c3c0-df1b-4748-afe3-9dc5949b2e00
Correlation Id: 648a742a-eb9a-4d95-82ef-2368a40a1317
Timestamp: 2020-09-24T14:30:06Z
Message: AADSTS700016: Application with identifier '290d2113-4ab2-40bd-8458-39e07ca0035b' was not found in the directory 'd3aed393-af94-47d5-b84f-aa8a17c13425'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

I can confirm that the Application Id quoted above refers to the Azure AD application set up during the Office 365 setup. I am however unsure as to the nature of the quoted directory identifier.

On closer inspection of the problem it seems that the users experiencing this issue have logged into another Office 365 tenancy on the same browser they are attempting to access our institutional tenancy. Our recommendation for now has been to use another browser to login. This is unsustainable and I would like to know if anyone else has experienced this problem and if there is a more permanent workaround that can be put in place.

thanks,
Cathal.

**Comment by weilai-irl** [comment]
The root of the issue is indeed what @coriordan found out - a user would have an activity session from other Office 365 tenants in their browser, and when trying to access the login page, Moodle would try to login the user from the other tenant, but as the resource is not created in the configured tenant, the error was thrown.

The solution of the issue is to update the following two settings from generic values to tenant specific values:
 - "Authorization Endpoint" of auth_oidc
 - "Token Endpoint" of auth_oidc

The default settings for both point to generic tenant-neutral endpoints, i.e. https://login.microsoftonline.com/common/oauth2/authorize and https://login.microsoftonline.com/common/oauth2/token. If they are set to tenant specific endpoints, e.g. https://login.microsoftonline.com/c4dcd496-d273-4b1c-8e6a-db7a12c3b950/oauth2/authorize and https://login.microsoftonline.com/c4dcd496-d273-4b1c-8e6a-db7a12c3b950/oauth2/token respectively, only users from the tenant will be used for authentication.

This will only apply tenant specific login page with custom design, if it has been configured. 

Regards,
Lai
