### ISSUE TITLE
The name of groups / teams should upgrade when changing course name

### ISSUE THREAD

**Issue by darius-m** [microsoft/o365-moodle#1396]
The event handler for course update should change the name of the linked group or team. However, the handler only does this for sharepoint sites, if they are enabled.

Steps to reproduce:
 - create a course (optionally: add an user with the `o365:teamowner` capability)
 - sync the course to create a team
 - change the course name
 - result: the name of the course is different from the name of the team it is linked to

Expected result: the name of the group (or team, if an owner is present) should update accordingly.

**Comment by weilai-irl** [comment]
Hi @darius-m,

Thank you for the suggestion.

However from our experience, the expected behaviour on course name change varies depending on client. The idea is Team created from course would only have the course name initially, but from there, they can become different. In reality, we have seen some sites that we support making changes to course names after initial sync, and some other sites making changes to Team names. I don't think there is one solution for all here.

A possible better approach would be to make this a configuration, which can be toggled by site admin. Please log this as a feature request if needed. This will be a low priority one though considering the amount of open issues.

Regards,
Lai

**Comment by darius-m** [comment]
Hello!

Yes, having it as a feature request would be great! However, I'm not, however, sure I can assign the label myself. How would the correct procedure be?

All the best,
Darius

**Comment by weilai-irl** [comment]
@darius-m

Hi Darius,

You won't be able to do it on your side. You will need to be the maintainer of a repository to add tags etc. I'll make changes accordingly.

Regards,
Lai

**Comment by weilai-irl** [comment]
The feature request in this one is:

Add a new configuration to local_o365 to control if Teams names need to be updated when course names in Moodle are updated.

Note this will still be a one-way sync from Moodle to Teams, i.e. Teams name changes will not be synced back to Moodle course.

**Comment by darius-m** [comment]
If you have a chance, take a quick look at #1441

**Comment by weilai-irl** [comment]
Hi @darius-m,

Thank you for making the pull request.

At a glance, the change looks good to me; however, a setting needs to be added to the local_o365 to allow site admins to toggle this feature on and off. This change may have big impact on Team names, so I wouldn't feel comfortable pushing this change to the release without giving site admins options to retain how things are working now.

I'll try to make the necessary changes for it, and include this in the November release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @darius-m,

As mentioned in my previous comment, I have added a configuration "Update Teams name on course update" in the "Course Sync" section on the "Sync Settings" tab of the "Microsoft 365 Integration" configuration page, to allow site admins to control either to update Team name when course name is updated.

The change has been included in the latest 3.9.4 and 3.10.1 release. Please check them out.

Thank you again for your contribution.

Regards,
Lai
