### ISSUE TITLE
No token available for usersync

### ISSUE THREAD

**Issue by AntonT76** [microsoft/o365-moodle#1435]
actually we have the problem that the user sync will synchronise only a part of the users (only about 80 % of our users have been synchronised). After that, sychronising will not work anymore (no synchronising of new users and also of existing users).

During the user sync we get this output of the CRON job:
```
Execute scheduled task: Synchronisieren Sie Benutzer mit Azure AD. (local_o365\task\usersync)
...... Starting sync
...... No skiptoken (full) stored.
...... Forcing full sync.
...... Contacting Azure AD...
...... Error in full usersync: No token available for usersync
...... Resetting skip and delta tokens.
...... Got response from Azure AD
...... Clearing skiptoken (full) (none received)
...... No users received to sync.
...... Sync process finished.
... used 3 dbqueries
... used 0.11583209037781 seconds
Scheduled task complete: Synchronisieren Sie Benutzer mit Azure AD. (local_o365\task\usersync)
```

Together with the Microsoft Support we found out that the problem based on a token issue, e.g. [https://github.com/microsoft/o365-moodle/issues/1271](https://github.com/microsoft/o365-moodle/issues/1271) - this issue was fixed in 3.7 and later.

The token problem still exists in 3.5. Actually we can't do an update to newer Moodle versions (e.g. 3.9) during the semester/term - such great updates will be done only in school holidays (e.g. summer 2021).

We have more than 10.000 users, so user synchronisation is very important for us. So I would like to submit this request as an issue which will be also fixed in 3.5.

thanks, best regards
Anton

**Comment by weilai-irl** [comment]
Hi @AntonT76,

The maintenance of the plugins in the set is inline with the maintenance status of Moodle core, therefore bug fixes for general  bugs in 3.5.x ended already, while bug fixes for security issues will end in May 2021. Therefore a new release for Moodle 3.5 which contains feature bug fixes is not on the map.

If you find the github issue in which the bug was fixed, you should be able to manually apply the fix easily enough. The issue #1271 is linked with two pull request, #1310 and #1311, for Moodle 3.7 and 3.8 respectively. You will need to go to the pull request (the 3.7 one, as it should be closer to 3.5 version), and look in the "files changed" tab, which will show you all the changes in the pull request.

Hope it helps.

Regards,
Lai
