### ISSUE TITLE
Site Errors and Login Problems changing accounts from manual to openid

### ISSUE THREAD

**Issue by naldo-gomes** [microsoft/o365-moodle#1488]
Hello guys!

I have a problem to macht users in moodle.

When trying to access with the user we received the message that "OpenID Connect, you'll need to use the Microsoft block" needs to be configured
However, the user is an end user and does not have access to the Microsoft block.
We have already changed the user id directly in the database, table - mdl_auth_oidc_token linking to the id that was previously 0.
I need help to solve this problem.
This is the error that is occurring

![image](https://user-images.githubusercontent.com/75033869/101183800-bbaced80-362e-11eb-9e21-d754b197e5ef.png)

**Comment by nenorojas** [comment]
Hi @naldo-gomes , what's the Moodle version you are using and version of the plugins auth_oidc, local_o365 and block_microsoft?

**Comment by naldo-gomes** [comment]
> Olá @ naldo-gomes , qual é a versão do Moodle que você está usando e a versão dos plug-ins auth_oidc, local_o365 e block_microsoft?

Hi Nenorojas!

These are the versions:

Moodle Version - 3.5.1+ (Build: 20180817)

auth_oidc Version - 3.5.0.2

Local_O365 Version - 3.5.0.2

**Comment by nenorojas** [comment]
Hi @naldo-gomes ,

We recommend to upgrade your Moodle version to 3.5.15 and plugins (auth_oidc 3.5.0.5 and local_o365 3.5.0.6) to latest version available to be sure that you are not running into specific bugs. We also recommend to upgrade to 3.9 that is the newest LTS Moodle version asap because the plugins compatible with 3.5 are not receiving bug fixes or new features anymore. 

What you can try is:

- Delete the mapping record in "local_o365_connections", by clicking the 
"unmatch" button on the "manage connections" page (/local/o365/acp.php?mode=userconnections) for the user.
 - Start a run of the sync users task, with "Perform a full sync each run" option enabled.
The sync users task run will create the mapping of the users in the "local_o365_objects" table, as they fall into the standard mapping rules.

Any reason why you do not allow students to see the Microsoft block?

Regards

**Comment by weilai-irl** [comment]
Hi @naldo-gomes,

Please follow suggestions by @nenorojas first.

For more details about the manual connection feature, and the error in your screenshot, please read on.

The user connections feature is designed to allow linking a user who's not using auth_oidc to an Office 365 account in the tenant that's configured in auth_oidc/local_o365 plugins. Here are the steps to fully set up a connection:
 0. Let's first assume that:
   - there is a Moodle account with username "a123" and authentication type manual (it can be any auth type except for auth_oidc).
   - there is an Office 365 account with username "abc123@example.com", and there isn't a Moodle user created from the Office 365 account yet.
 1. Moodle site admin goes to the "Manage User Connections" page, and search for the Moodle user.
 2. Moodle site admin clicks the "Match" button for the user, and enters "abc123@example.com" in the "Office 365 username" field, and saves changes.
 - This will create a record in mdl_local_o365_connections table.
 - On the "Manage User Connections" page, the connection status of the user will turn to "Matched with existing user. Awaiting completion."
 - Note that at this stage, a connection is not fully set up yet. If the Office 365 user tries to login to Moodle using OpenID Connect authentication now, the user will see the exact error as shown in your screenshot. It basically means that although authentication is working for the Office 365 user, Moodle cannot login the user because it has a record that the Office 365 username belongs to a different Moodle user. The user needs to log in to Moodle using the authentication type of the account.
 3. The Moodle user "a123" needs to login normally, e.g. using password if the auth type is manual, and visit a page that contains the Microsoft block. Normally this should be the dashboard page of the site.
 4. In the Microsoft block, the user should see a message like in the screenshot_1 attached, which contains title "You are almost connected to Office 365". The block also contains a link to "Log in to Office 365", which is another Moodle page that's showing connection status and options, see screenshot_2. Clicking the link "Click here to login" will ask the user to login to Office 365, and successful login will finish the connection.
 - Note this will create new records in both mdl_local_o365_objects and mdl_auth_oidc_token tables. It's not recommended to manually change data in these tables as it may introduce inconsistency. 
 - You may need to give "auth/oidc:manageconnectionconnect" or "local/o365:manageconnectionlink" capability to "Authenticated user" role to allow users to see the connect option in the Microsoft block.
 - After successful login, the connection status of the user on the "Manage User Connections" page will turn to "Connected".

I hope this explains the workflow well.

Please let me know if you have more questions.

Regards,
Lai
