### ISSUE TITLE
Class Notebook integration

### ISSUE THREAD

**Issue by vinhub** [Microsoft/o365-moodle#149]
- For each Office 365 Group (which corresponds to a Moodle Course), we will replace the Office 365 Group Notebook (which lives in group’s Site Assets library) with a OneNote Class Notebook (using the API).    
 
- To do this add a special header to the API call to replace the Group’s default OneNote Notebook.  Everything is the same as outlined in the [MSDN doc ](https://msdn.microsoft.com/office/office365/howto/onenote-classnotebook)on creating a OneNote Class Notebook, EXCEPT that you have to include a User Agent header along with the POST request with the value "Homeroom/1.0". This will make it so that the OneNote Class Notebook is not created in OneDrive but rather in the Group Site Assets library.  
 
- Make all of the Office 365 Group Admins as “Teachers” in the Class Notebook (and everybody else as “Students”). 

- Today we don’t make Moodle Teachers for a course into Admins so we will need to make this change first.
 
- Link to the “Course Notebook” from the Course Groups UI (underneath Calendar).
![unnamed](https://cloud.githubusercontent.com/assets/1817329/16019962/9e4623e2-3160-11e6-9202-4c8a2e1036fb.jpg)
 
- Add “Course Notebook” to the User Group Customization UI.
![image002](https://cloud.githubusercontent.com/assets/1817329/16019933/7e263ffc-3160-11e6-9817-819de28041ec.jpg)

**Comment by number33** [comment]
@vinhub are you currently working on this issue for the current milestone?  If so, I'll add it.

**Comment by vinhub** [comment]
Also need to include "Moodle teachers are not being set as admins for the o365 group" as a part of this.

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/165

**Comment by NageshTembhurnikar** [comment]
Test Cases:
**# Add “Course Notebook” to the User Group Customization UI.**

Goto Site Administration -> Plugins -> Local -> Microsoft Office 365 Integration -> Options -> Integration Features -> User Groups.
Check Customize Groups radio box and click on save button. Now you will see a link "Customize groups", click on link. You should see "Course Notebook" column is present and you can select the checkbox for each group/course according to your needs.
In Bulk operation section
Click on Course Notebook : "Enable All", It should check all the checkboxes for "Course Notebook" for all groups.
Click on Course Notebook : "Disable All", It should uncheck all the checkboxes for "Course Notebook" for all groups.
Hit "save changes" to save all your changes.

**# Link to the “Course Notebook” from the Course Groups UI (underneath Calendar).**

Goto Course page-> Microsoft Block -> Course Group, here you can see the link named "Course Notebook". When you click on link it will point you to the o365 notebook for the course.
If you see the message "This Office 365 group will be created shortly, please try again later." it means o365 group for course is not created yet by cron job. Check your group setting mentioned in above issue if everything is correct, come back again after running cron job.

**# For each Office 365 Group (which corresponds to a Moodle Course), we will replace the Office 365 Group Notebook.**

Goto Course Groups in microsoft block, then click on "Course Notebook" link, o365 will setup a notebook for group if not present and opens the notebook.
After running cron job, goto same link you will see a "class notebook" instead of "notebook" for the group.

**# We don’t make Moodle Teachers for a course into Admins so we will need to make this change first.**

Create new course then enroll users to that course with roles like student, teacher, non-editing teacher.
After running cron job, it will create a group in office 365 and add enrolled members to o365 group. Role teacher, non-editing teacher will be added as owner of o365 group and other role will be added as member of group.
