### ISSUE TITLE
Moodle Teams Tab unable to save

### ISSUE THREAD

**Issue by anritschel** [microsoft/o365-moodle#1499]
Hello,

We recently installed moodle for our organization, but when we go to add the tab to a Team the save button is grayed out. I have tried everything i can think of to get this to work and even fully re-built the o365 integration thinking I may have missed something but no luck. 
![moodleScreenshot](https://user-images.githubusercontent.com/39089438/102367243-2808e480-3f7f-11eb-9b48-c3f36b0a3d53.png)

**Comment by bjoerrrrn** [comment]
I have the same problem. Did you solve this? :-(

**Comment by ozgurkk** [comment]
Hi,

As i read, if moodle verison is over 3.5  integration will not work, because of suitable plugin not yet released. 
I  didnt integrate with moodle versions with 3.8 , 3.10. Integration steps did perfect but cannot add tab as mentioned above.
 
Is there any workaround to  make it work.

There are 2 of my customers (universities )waiting for this  integration.

**Comment by weilai-irl** [comment]
Hi @Ethershade,

Thank you for posting the screenshot. It helps explaining the issue a lot.

I see in your screenshot that you are trying to open the Moodle tab configuration page, and in the iframe, it shows the Moodle dashboard page. This seems wrong.

When trying to open the Moodle tab configuration page, the page in the iframe should have URL like https://url.to.moodle/local/o365/teams_tab_configuration.php. The page would do SSO, and show a list of courses that the correct user can access. It shouldn't redirect users to the Moodle dashboard page.

I'd suggest you to open Teams in a web browser, open developer tool, and monitor the actions in the networks tab, to see the sequence of redirect. The purpose would be to confirm that the correct tab configuration page is reached. Please try this and post back your findings.

@bjoerrrrn, and @ozgurkk, please confirm if you are seeing exactly this behaviour (showing Moodle dashboard page in iframe). If you see other pages, it's quite likely that it's a different issue, and I'd suggest you reporting as new github issue.

Regards,
Lai

**Comment by Ethershade** [comment]
Hello wailai-irl,

Thank you for taking the time to look into this for us. I have attached a new screenshot that shows what you were requesting in the network monitor. Everything looks good and I am able to do a Save, but only when working with the integration through the web browser, are there any plans to get this working the same on the desktop app?

Thank you,

Andrew Ritschel

**Comment by weilai-irl** [comment]
Hi @Ethershade,

Thank you for the update.

This is actually working in our tests from Windows and MacOS Desktop apps. At the back end the Moodle tab works in the same way as in Teams web apps and in the Desktop apps, so there's no reason why it doesn't work.

It is actually possible to enable developer tools from Teams apps too, which may help. In order to do it, you will need to click the Teams desktop icon 7 times, and you should see an extra menu item "Development". From there, you can enable DevTools, similar to what you would have in browsers. Please give it a try and see if you can find the network activities when you open the Moodle tab configuration page.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @anritschel,

Could you confirm if your Moodle site is publicly accessible, and have a valid public signed SSL certificate please.

Teams desktop/mobile app doesn't support embedding sites without public signed certificate, but Teams web app would work.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi all,

We have made a new release of the local_o365 plugin for Moodle 3.9 and 3.10 that contain improvements in Moodle and Teams integration have finally arrived. The new version should fix most issues in the integration, if not all. The release notes for [Moodle 3.9](https://github.com/microsoft/o365-moodle/releases/tag/v20210629_m310) and [Moodle 3.10](https://github.com/microsoft/o365-moodle/releases/tag/v20210629_m39) are linked.

Please upgrade your plugin [local_o365](https://moodle.org/plugins/local_o365/versions) (and [auth_oidc](https://moodle.org/plugins/auth_oidc/versions) which it depends on) to the latest version and try it out. Please report back any remaining issues found in this issue. The issue will be kept open for one month from today, and will be closed if most issues are confirmed resolved.

Regards,
Lai

**Comment by weilai-irl** [comment]
Issue closed one month after release.
