### ISSUE TITLE
Moodle not creating Student Teams

### ISSUE THREAD

**Issue by Polomints21** [microsoft/o365-moodle#1551]
Hi,

We installed and have used the Moodle plugin "Microsoft Office 365 Integration" since last year, it was working fine for last semester and is working ok now but one issue has me puzzled, before when a team was created it was created as a Class Team, now when the teams are created, they are not class teams and are missing features like class notebook, even though we have ticked all the correct features in settings. Have you heard of this happening before?

![image](https://user-images.githubusercontent.com/78027753/105849321-1f70e880-5fd8-11eb-96d5-ebeb52abff43.png)

**Comment by nenorojas** [comment]
Hi @Polomints21 

All what these options do is to control what links are available in the "Course Group" link in the Microsoft block, please see https://github.com/microsoft/o365-moodle/issues/1508. They don't affect services created from course sync.

Can you please check if this issue is still happening with latest version of the plugin?

Regards

Oswaldo

**Comment by weilai-irl** [comment]
Hi @Polomints21,

The reason you saw standard teams created instead of class teams could be that at the time of initial course sync, there was no suitable team owner, e.g. teacher, enrolled in the course, so a group was created first. At a later time, when a suitable team owner is enrolled to the course, the integration would try to create a team from the existing group, and due to limitations of the Graph API used, only standard groups can be created this way.

Most recent release of the plugins contains an option to not "fall back" to groups in case no suitable team owner is enrolled in the course, which can be useful in your case. Please check it out.

Regards,
Lai
