### ISSUE TITLE
moodle-auth_oidc - User profile information not updating from token

### ISSUE THREAD

**Issue by nbartley** [microsoft/o365-moodle#1556]
Good Day,

Moodle 3.10 and 3.8. No o365 plugin installed. SSO via Keycloak.

Currently, it does not appear that the user information is ever updated from the token after the user account is created. When a users email address or name changes, Moodle still retains the original registration information.

**Comment by nbartley** [comment]
Follow up: Investigated the code a bit further.

In an earlier version of the plugin, loginflow/base.php lines 40-50 were set to "onlogin" which updated the Moodle Profile every time with SSO information. 

When the o365 mapping was introduced, it was changed to "oncreate" and overriden by the o365 mapping if required.

These settings should really be changed back to "onlogin" for users who are not using the o365 plugin with it. The "oncreate" is rather counter-intuitive to the plugins purpose.

**Comment by jbriggscmet** [comment]
We're having a similar issue. Accounts are created without issue, however on subsequent logins everything apart from the first name is updated.

Our mappings are configured correctly:

**Comment by weilai-irl** [comment]
Hi all,

@jbriggscmet, The issue you mentioned is different from the one originally reported in this issue. Your particular issue is known to us and will be fixed in the upcoming release later this month.

@nbartley, I'll look into the issue that you mentioned in the next release. I recall there was some reason it was set to "oncreate", but I can't remember what it was. I'll try to find out.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @jbriggscmet,

The issue you reported should have been fixed in the 3.9.4 and 3.10.1 release made available last week. Please upgrade to the version and try it out.

Regards,
Lai

**Comment by nbartley** [comment]
@weilai-irl Specifically my issue was not resolved with the latest update. classes/loginflow/base.php lines 41-50 are still set to oncreate rather than onlogin.

**Comment by weilai-irl** [comment]
Hi @nbartley,

Yes, I confirm it wasn't included in the March 2021 release, and it's why I didn't tag you for test. The message was for jbriggscmet on the issue he reported. That issue was spotted elsewhere before (so I said "was known to us") and a fix was ready even before it was reported here, but was only included in the March release.

We intend to introduce a major upgrade of the field mapping features in the May 2021 release, and will move the synchronisation of most standard profile fields from local_o365 to auth_oidc, and allow choosing between oncreate and onlogin on each of them. Please stay tuned.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi all,

Due to scheduling difficulties, the "major upgrade" of the field mapping feature has been pushed back to the next release after June 2021, which means this issue will stay open for another while.

Regards,
Lai
