### ISSUE TITLE
Missing Permissions

### ISSUE THREAD

**Issue by Guyver1wales** [microsoft/o365-moodle#1617]
Yesterday I ran the script to create our app registration.
I followed the instructions in the README.

Our developer, who did the moodle plugin setup after I had provided the app registration ID and secret configured the plugin, but after day now letting it settle down moodle is showing that the following permissions are missing
![missing_permissions](https://user-images.githubusercontent.com/22168798/110629954-b1a20a00-819c-11eb-9dc4-fc63d9dc6658.png)

Have I done something wrong? (I don't think so as the PowerShell script is basically idiot proof as there's very little to input)

Or is this an issue with the script?

How do I resolve these permissions in AzureAD, what exact Microsoft Graph permissions do I need to the app registration to resolve these error messages?

**Comment by Guyver1wales** [comment]
for now I have added the two Missing Microsoft Graph permissions to the app registration. and our dev will check the moodle plugin later on today to see if its resolved.

**Comment by weilai-irl** [comment]
Hi @Guyver1wales,

I acknowledge the issue, and I confirm you haven't done anything wrong. This issue is known to us - the PowerShell script misses some permissions required by later version of the plugin. Simply put - the permission check has been updated to be performed on all required permissions, but the PS script hasn't.

We are working with Microsoft to update the PS script included in the local_o365 plugin and hope to have this resolved in the May or July 2021 release. At the mean time, please add the required permissions manually to ensure all features work.

Regards,
Lai
