### ISSUE TITLE
Error 'Field "resource" does not exist in table "auth_oidc_token"' when upgrading from releases before 3.8.0.1 (2020020302) to 3.9.4 and 3.10

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#1635]
When upgrading from 3.5 plugin set to 3.9, the upgrade fails with the latest versions.
````
!!! Field "resource" does not exist in table "auth_oidc_token" !!!
!!
Error code: ddlfieldnotexist !!
!! Stack trace: * line 672 of /lib/dml/moodle_database.php: dml_exception thrown

line 1403 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
line 614 of /local/o365/db/upgrade.php: call to moodle_database->get_records()
line 692 of /lib/upgradelib.php: call to xmldb_local_o365_upgrade()
line 1917 of /lib/upgradelib.php: call to upgrade_plugins()
line 193 of /admin/cli/upgrade.php: call to upgrade_noncore() !!'
````

This is because the resource field in auth_token table has been renamed to tokenresource earlier.
````
if ($result && $oldversion < 2020110901) {
    // Rename field resource on table auth_oidc_token to tokenresource.
````

**Comment by weilai-irl** [comment]
@kkiiskin,

Hi Kimmo,

I acknowledge the issue. For a temporary solution, you can upgrade to the previous version (3.9.3 or 3.10.0 releases) first, and then upgrade to the latest versions. I'll add such information in the release note.

As the database changes to auth_oidc_token table have been made to your site, you may need to fix the name difference locally on your site. To do this, replace line L615 to 618 of local/o365/db/upgrade.php with the following.
```
            foreach ($oldgraphtokens as $graphtoken) {
                $graphtoken->tokenresource = 'https://graph.microsoft.com';
                $DB->update_record('auth_oidc_token', $graphtoken);
            }
```

This is a once-off change, so as soon as the plugin has been upgraded, you can revert it back.

Please give it a try and let me know if it works.

Regards,
Lai

**Comment by kkiiskin** [comment]
Hi

we did the same thing you suggested and the upgrade goes through.
Just raised this issue to help future upgrades, we still have some 3.5->3.9 to do :)

Thanks for the quick response.

**Comment by cDMB41** [comment]
I have this issue as well. My difference is this is going from 3.9.4. I have tried the fix above and it does not work.

**Comment by weilai-irl** [comment]
@cDMB41,

Could you confirm the local_o365 plugin version you are having this issue in please. If you saw this after an upgrade, please also indicate from which version you upgraded from.

Could you also show me the fields in the "mdl_auth_oidc_token" table of your Moodle database please. If possible, it would also help if you can tell me what values are in the field "resource" or "tokenresource" for most users in that table.

Regards,
Lai

**Comment by cDMB41** [comment]
This was an upgrade from Moodle 3.9.7 to 3.10.4. I tried to upgrade the plugins, but when I do, it goes to upgrade the Moodle DB, then I can't get past it due to the above error.
The initial version of the local_365 is 3.9.4 2020071504 and I am trying to upgrade to the 3.10 version.
How would I show the files in the DB table?

**Comment by weilai-irl** [comment]
Hi @cDMB41,

I acknowledge the issue. There is a bug in the upgrade script of local_365 plugin, which would try to run renaming from "resource" to "tokenresource" twice if upgrading from 3.9.7 to 3.10.4.

The upgrade script will be updated in the next release to solve this. At the mean time, you can comment out (or delete) from [line 655](https://github.com/microsoft/o365-moodle/blob/6a210db3779a6da9db544139ccb4e0d12873d199/local/o365/db/upgrade.php#L655-L668) to [line 730](https://github.com/microsoft/o365-moodle/blob/6a210db3779a6da9db544139ccb4e0d12873d199/local/o365/db/upgrade.php#L730) so that upgrade and proceed.

Regards,
Lai

**Comment by cDMB41** [comment]
That didn't work. Here is the error. I commented out the lines in upgrade.php as above.

auth_oidc
Field "resource" does not exist in table "auth_oidc_token"

More information about this error

×Debug info:
Error code: ddlfieldnotexist
×Stack trace:
line 683 of /lib/ddl/database_manager.php: ddl_field_missing_exception thrown
line 198 of /auth/oidc/db/upgrade.php: call to database_manager->rename_field()
line 697 of /lib/upgradelib.php: call to xmldb_auth_oidc_upgrade()
line 1922 of /lib/upgradelib.php: call to upgrade_plugins()
line 713 of /admin/index.php: call to upgrade_noncore()

**Comment by weilai-irl** [comment]
Hi all,

The fix to the issue, which prevents upgrade scripts to run multiple times, has been included in the latest release of the plugin. 

The issue will not closed now.

Regards,
Lai
