### ISSUE TITLE
Mapping datafields

### ISSUE THREAD

**Issue by kruithre** [microsoft/o365-moodle#1671]
Hello,

We are currently using the plugin for Azure AD synchronisation on a standard Moodle setup.
Pretty soon we will be moving to a Moodle Workplace environment.
In order to make use of the extended functionality (e.g. approval workflow etc) I'm looking for a way to integrate things like role, manager etc). Based on the screenshot on the plugin page it seems to be able to do that. However, I cannot fidn a way to map the fields as the destination fields as shown in the screenshot are not available to me (looking on the standard moodle setup).

Is this because the data is not yet in the AD feed? Is it because Moodle standard cannot store that info (and the screenshot is from a Moodle workplace environment?) or ......

Looking for some tips to solve this and to configure the feed

Thanks in regards!
Remco
![mapping moodle](https://user-images.githubusercontent.com/83588535/116876358-a14a6080-ac1c-11eb-9745-04aeab362be8.JPG)

![image](https://user-images.githubusercontent.com/83588535/116875933-fdf94b80-ac1b-11eb-80c6-492287748c32.png)

**Comment by weilai-irl** [comment]
Hi @kruithre,

I'm not sure what is your expected behaviour for mapping the "roles" and "manager" fields. I can only describe what the field mapping feature does for the two named fields.
 - For the "roles" field, it will fetch the directory roles that the user has using the [user: getMemberObjects API](https://docs.microsoft.com/en-us/graph/api/user-getmemberobjects?view=graph-rest-1.0&tabs=http) and filtering by resource type "role", and save the "displayName" attribute of the role resources in a comma separated string. This is then saved in the Moodle profile field configured. Notably this will not change the roles of the user in Moodle in any context.
 - For the "manager" field, it will get the the manager of the user from Azure AD using the [list manager API](https://docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&tabs=http), and save the "displayName" attribute the of manager user as a string to the configured Moodle profile field. It will not try to locate the manager user in Moodle, and set up any relation between the two Moodle users.

Please review the current behaviour, and see if it answers your questions.

Regards,
Lai
