### ISSUE TITLE
auth_oidc: doesn't support multiple tenants

### ISSUE THREAD

**Issue by duranchen** [microsoft/o365-moodle#1750]
Hi Sir,

When local_o365 plguin is set up with multiple tenants, a user should go to commont endpoints,  " https://login.microsoftonline.com/common/oauth2/authorize"  to authorize, and "https://login.microsoftonline.com/common/oauth2/token" to get tokens, but the common endpoints are replaced with main tenant endpoints on the code here - 
https://github.com/microsoft/o365-moodle/blob/1a6d4ad384ce2a83f5a1be2d42e3b30762bb0886/auth/oidc/classes/loginflow/base.php#L421

**Comment by kkiiskin** [comment]
Hi

I came across this too. Is the solution to just change the endpoints back to common ones @weilai-irl ?
Does it require anything else like deleteing/updating tokens?

**Comment by duranchen** [comment]
> Hi
> 
> I came across this too. Is the solution to just change the endpoints back to common ones @weilai-irl ?
> Does it require anything else like deleteing/updating tokens?

Hi @kkiiskin，
you also need to delete/commnet the code below on o365-moodle/auth/oidc/classes/loginflow/base.php line 421.
        if ($aadtenant) {
            if ($authendpoint == 'https://login.microsoftonline.com/common/oauth2/authorize') {
                $authendpoint = str_replace('common', $aadtenant, $authendpoint);
            }

            if ($tokenendpoint == 'https://login.microsoftonline.com/common/oauth2/token') {
                $tokenendpoint = str_replace('common', $aadtenant, $tokenendpoint);
            }
        }

**Comment by weilai-irl** [comment]
Hi @duranchen,

Thank you for reporting this. You are spot on - when using multi tenants, the endpoints need to use "common" path, and any tenant specific endpoint will result in users from additional tenants fail to login.

My original intention to make the change was to provide a more personalised login experience for users, but clearly I didn't consider the multi tenants case.

The issue should be fixed by the linked pull requests, which will be included in the next release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @duranchen,

New version of the plugins that contain the fix to the multi tenant issue has just been release. Please upgrade your plugins and confirm if they fix your issues.

I'll keep the issue open for another month, and close it if no more issue is reported.

Regards,
Lai
