### ISSUE TITLE
Keycloak connected to Moodle, Keycloak User ID is being set as Username

### ISSUE THREAD

**Issue by ignBiometrical** [microsoft/o365-moodle#1751]
How would I have the plugin use preferred_username instead of the User ID. Right now, this is not working.

**Comment by weilai-irl** [comment]
Hi @ignBiometrical,

I'm afraid there isn't an existing feature to allow Moodle site admins to choose which claim in the token to be used as Moodle username. 

As you can imagine, most of the development was done and tested on Azure AD IdP. We don't have a Keycloak IdP set up to test auth_oidc against.

I confirm that `preferred_username` is a claim available in Azure AD too, so it is a technical possibility for it to be used as username. However in Azure AD the claim is mutable thus can be changed over time and is highlighted for unsuitable for making authentication decisions.

In the current logic, the plugin uses the `upn` claim in the ID token as username, and would fall back to the unique ID if it fails.  I understand that the `upn` is not a standard claim in Keycloak. At a high level, you have two options here:

1. Try to create `upn` as a custom claim in Keycloak, and set it have the same value as the `preferred_username` claim. I'm no expert in Keycloak so I'm not 100% sure whether this is feasible; but if this can be achieved, it should achieve what you desire.
2. If option 1 is infeasible, it's technically possible to add a logic in auth_oidc to check for the existence of the `preferred_username` as a fallback of the `upn` claim check (and maybe add an option to indicate if this check needs to be performed). However the difficulty on our side here is how we can test this since we don't have a Keycloak environment.

Could you give the first approach a try to see if it works please.

Regards,
Lai

**Comment by ignBiometrical** [comment]
Oop, sorry. Completely forgot about this, I mapped UPN to username on my client, so this has been solved.

**Comment by ignBiometrical** [comment]
Also new question, @weilai-irl. is it possible for me to have it auto sync users every let's say like 30 minutes, as well, the profile scope passes through any roles for the user, is it possible for if the user has ROLE-A they become an admin?
