### ISSUE TITLE
 invalid team ID

### ISSUE THREAD

**Issue by B0ulbi** [microsoft/o365-moodle#1784]
Hello,
we have a problem with teams synchronization 
Could not create class team for #3387. Reason: invalid team ID
Syncing group membership for course #3387
Could not find group object ID in local_o365_objects for course 3387. Please ensure group exists first.
Could not create class team for #3400. Reason: invalid team ID
Syncing group membership for course #3400
Could not find group object ID in local_o365_objects for course 3400. Please ensure group exists first.
Could not create class team for #3401. Reason: invalid team ID
Syncing group membership for course #3401
Could not find group object ID in local_o365_objects for course 3401. Please ensure group exists first.
Could not create class team for #3402. Reason: invalid team ID
Syncing group membership for course #3402
Could not find group object ID in local_o365_objects for course 3402. Please ensure group exists first.
Could not create class team for #3405. Reason: invalid team ID

Can you please help us.
moodle  3.9.9 (Build: 20210729)
plugin  local_o365 3.9.6 build 2020071509

Thanks a lot

**Comment by weilai-irl** [comment]
Hi @B0ulbi ,

It looks like to the Graph API call to create teams from courses failed somehow.

The first step I'd suggest you to do is to ensure that the Microsoft 365 integration is in a working condition. Could you go to the Microsoft integration configuration page (https://URL.TO.MOODLE/admin/settings.php?section=local_o365), click the "Update" button in the "Verify setup" section, can confirm the results of the verification please. If any issue is reported, please fix it and rerun the task; otherwise please read on.

For the next level of troubleshooting, you will need to make some code change to add additional debugging function to understand what exactly is returned in your Graph API calls. Please replace[ line 335 to line 351 of local/o365/classes/feature/usergroups/coursegroups.php](https://github.com/microsoft/o365-moodle/blob/1faac0e583e84f2620ca2fdfffebc8342afb245b/local/o365/classes/feature/usergroups/coursegroups.php#L335) with the code below.
`
        try {
            $teamid = null;
            $response = $this->graphclient->create_class_team($displayname, $description, $ownerid);
            var_dump($response);
            if (is_array($response) && array_key_exists('Location', $response)) {
                $location = $response['Location'];
                $locationparts = explode('/', $location);
                foreach ($locationparts as $locationpart) {
                    if (substr($locationpart, 0, 5) == 'teams') {
                        $teamid = substr($locationpart, 7, 36);
                    }
                }
            }
        } catch (\Exception $e) {
            var_dump($e);
            $this->mtrace('Could not create class team for #' . $course->id . '. Reason: ' . $e->getMessage());
            return false;
        }
` 

If you run the groupcreate task again, it should output more information. Please paste back the output in a new comment when you get them.

Regards,
Lai

**Comment by B0ulbi** [comment]
Hello @weilai-irl 
Thank you for your answer.
Actually a moodle administration had add the capacity teamsowner to manger role and this is have blok team creation.
The problem is resolved

**Comment by OscarTheFabulous** [comment]
Greetings!
We are having this issue right now. Roles are correct.
Here is the output from the modified groupcreate task

string(1808) "{"error":{"code":"BadRequest","message":"Failed to execute Templates backend request CreateTeamFromTemplateRequest. Request Url: https://teams.microsoft.com/fabric/emea/templates/api/team, Request Method: POST, Response Status Code: BadRequest, Response Headers: Strict-Transport-Security: max-age=2592000\r\nx-operationid: bd692c8ae97a1149ae487cd91cdf7e1a\r\nx-telemetryid: 00-bd692c8ae97a1149ae487cd91cdf7e1a-89b00de86272fe49-00\r\nX-MSEdge-Ref: Ref A: 92D081F92EFA4D91B444F2A3767A78A5 Ref B: VIEEDGE3010 Ref C: 2021-09-14T10:43:06Z\r\nDate: Tue, 14 Sep 2021 10:43:06 GMT\r\n, ErrorMessage : {\"errors\":[{\"message\":\"Error when calling Middle Tier. Message: ''. Error code: 'UnableToGenerateValidTeamAlias'. Status code: BadRequest.\",\"errorCode\":\"Unknown\"}],\"operationId\":\"bd692c8ae97a1149ae487cd91cdf7e1a\"}","innerError":{"message":"Failed to execute Templates backend request CreateTeamFromTemplateRequest. Request Url: https://teams.microsoft.com/fabric/emea/templates/api/team, Request Method: POST, Response Status Code: BadRequest, Response Headers: Strict-Transport-Security: max-age=2592000\r\nx-operationid: bd692c8ae97a1149ae487cd91cdf7e1a\r\nx-telemetryid: 00-bd692c8ae97a1149ae487cd91cdf7e1a-89b00de86272fe49-00\r\nX-MSEdge-Ref: Ref A: 92D081F92EFA4D91B444F2A3767A78A5 Ref B: VIEEDGE3010 Ref C: 2021-09-14T10:43:06Z\r\nDate: Tue, 14 Sep 2021 10:43:06 GMT\r\n, ErrorMessage : {\"errors\":[{\"message\":\"Error when calling Middle Tier. Message: ''. Error code: 'UnableToGenerateValidTeamAlias'. Status code: BadRequest.\",\"errorCode\":\"Unknown\"}],\"operationId\":\"bd692c8ae97a1149ae487cd91cdf7e1a\"}","code":"BadRequest","innerError":{},"date":"2021-09-14T10:43:07","request-id":"c9c61324-3b40-40f4-af78-f8e8e378dbf8","client-request-id":"c9c61324-3b40-40f4-af78-f8e8e378dbf8"}}}"
Could not create class team for #13514. Reason: invalid team ID
Syncing group membership for course #13514
Could not find group object ID in local_o365_objects for course 13514. Please ensure group exists first.

Moodle 3.11.3 (Build: 20210913)
local_o365 3.11.0 (2021051700)
