### ISSUE TITLE
auth_oidc | opname does not support Multi-lang

### ISSUE THREAD

**Issue by dlazaroas** [microsoft/o365-moodle#1827]
Hi!

I'm working with the oidc plugin and I'm trying to set a multilang name for the connection's name and I'm setting the multilang option but it's not working properly having the multi-lang filter available on content and headers.

Did you know that? Is there any way we can set this with the multilang?

Kind regards,

**Comment by weilai-irl** [comment]
Hi @dlazaroas,

Could you explain what you are trying to do/achieve in a bit more details please. We'd like to help, but we're not sure about your situation.

Regards,
Lai

**Comment by dlazaroas** [comment]
Hi @weilai-irl 

I'm trying to use different language code on the plugin, i.e: 

<span lang="es" class="multilang">Accede</span><span lang="en" class="multilang">Log in </span><span lang="it" class="multilang">Accedi</span>

Which depending on your language should show the phrase, but I'm using this same code on the opname and it's not working correctly, it is cause of our system or a plugin thing?

Hope I explain myself well.

Kind regards,

**Comment by ikakouratou** [comment]
Hello @weilai-irl !

We'd like to reopen this ticket since this need has arisen again. 
The problem we're encountering is the following:
We're using Totara, an open-source learning management system based on Moodle (sorry if you're already familiarised with it, but just to make sure, I'll provide all the information) and we have installed this Open ID plugin on one instance of Totara. 
We would like to apply the multi-lang filter, (the html code for adding content in multiple languages) in the text that corresponds to the button called opname (Provider name), because now it is not supported. 
We can confirm that implementing multi-language filter is enabled across the platform. Could you help us out? I remain at your disposal for any further queries you may have or information you may need!
Best,
Ioanna

**Comment by weilai-irl** [comment]
Hi all,

I finally got some time to get my head around this request. It turns out to be a fairly easy one. The pull requests are linked to the issue, and it will be included in the upcoming September release of the plugins for Moodle 3.11 and 4.0.

@ikakouratou, I'm well aware of Totara, my employer - Enovation Solutions (https://enovation.ie) - is a Totara partner too. Unfortunately the Microsoft plugins are not directly supported in Totara as this is not covered by the contract we have in place with Microsoft. I'm afraid you will need to manually cherry pick the commit to your code in this case. Luckily the change is just one line and should be straightforward to do.

Regards,
Lai
