### ISSUE TITLE
Moodle failed to do delta sync user via API

### ISSUE THREAD

**Issue by Jerrysail** [microsoft/o365-moodle#1841]
Our Moodle admin reported that their process to do delta sync user return with the following error: Error in delta usersync: Error in API call: Sync must reach steady state within 30 days. What does this error means and what is the cause of it? This Moodle is using O365 Moodle plugin (https://github.com/microsoft/o365-moodle)

Incident time: Thu, Oct 7, 2021, 12:00 AM GMT+11

Complete log info from Moodle admin:
Execute scheduled task: Sync users with Azure AD. (local_o365\\task\\usersync)
... started 13:04:12. Current memory use 6.1MB.
...... Starting sync
...... Using skiptoken (delta)
...... No deltatoken stored.
...... Using delta sync.
...... Contacting Azure AD...
...... Error in delta usersync: Error in API call: Sync must reach steady state within 30 days.
...... Clearing deltatoken (none received)
...... Storing skiptoken (delta)
...... No users received to sync.
...... Sync process finished.
... used 4 dbqueries
... used 0.77270197868347 seconds
Scheduled task complete: Sync users with Azure AD. (local_o365\\task\\usersync)

**Comment by isanps** [comment]
Hi Oswaldo,

Greeting from UNSW. Jerry mentioned that you are looking for version information. Our Moodle admin advise me the following:
Moodle 3.9

Office 365 Integration
local_office365
3.8.0.1
2020020301

OpenID Connect
auth_oidc
3.8.0.1
2020020301

I read from Microsoft documentation that sometimes the delta sync return empty and need to do full sync. (https://docs.microsoft.com/en-us/graph/delta-query-overview) about Syncrhonisation reset. I am not sure if this is the root cause of our issue as from the log it shows "No deltatoken stored".

Kind regards,
Isan

**Comment by weilai-irl** [comment]
Hi @isanps,

Sorry for not getting back to you sooner.

I confirm that in case the delta token is invalid, the user sync task remove the last known token, and start a full delta user sync ON THE NEXT TASK RUN. So in theory if somehow the delta token received is always invalid, your user sync task runs could end up in a loop of saving invalid token and dropping it in the next run, but in reality I never see reporting of this happening. Checking your user sync task outcomes from time to time should be enough to detect rare situations like this.

I hope this answers your question.

Regards,
Lai

**Comment by tlock** [comment]
Hi Lai,

On this, if there is any consideration to improvement the sync process would be greatly appreciated as full or suspend sync takes 1.5 to 2 hours to complete.

Regards,
Tim

**Comment by weilai-irl** [comment]
Hi @tlock,

It is known to us that any user sync task run that would require getting full list of users (i.e. a full sync, or a sync that requires running the user suspension part) would take long time to finish on tenants with large number of users. This is due to the time taken to make the Graph API calls, and the time required to process the responses. I have performed reviews in this feature previously, aiming at reducing the time it takes to finish such task runs, and the current implementation is actually the results of these reviews (believe me it was even worse before). I can make another attempt, but because of the nature of it, I can't guarantee it will improve much.

At the meantime, I'd like to highlight that there's a logic in place to only run the user suspension/deletion part of the task once a day. The whole purpose of this limit to allow tenants with large numbers of users to use delta sync normally for most task runs during the daytime, and only to execute the user suspension/delete part (which may run for longer time) at a relatively quiet time.

Regards,
Lai

**Comment by tlock** [comment]
Hi @weilai-irl ,

Thanks, one thing that is missing with that feature that is missing is a configurable hour to run that suspend sync. We have found several issues:

- "tomorrow midnight" sets as UTC which means it will run during the day because we are in Australia
- execution on test, stage and prod environment run all at the same time making the issue worse

Regards,
Tim

**Comment by weilai-irl** [comment]
Hi @tlock,

Thank you for reporting the issues. I'll look at fixing them in the next release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @tlock,

The latest release from today contains an improved control of schedule to run the user suspension/deletion part in the user sync task. We have specifically tested the change in different Moodle default timezone settings and ensure it works according to the setting. Please check out this version and confirm if it works for you.

I'll keep the issue open for another month, but feel free to confirm the issue is fixed so it can be closed earlier.

Regards,
Lai

**Comment by weilai-irl** [comment]
Closed one month after release.
