### ISSUE TITLE
User Sync not changing to OpenID Connect

### ISSUE THREAD

**Issue by hcfhe-gshaw** [microsoft/o365-moodle#185]
Bringing https://github.com/Microsoft/moodle-local_o365/issues/10 over to the central o365 plugin page as per @jamesmcq suggestion.

The option "Switch matched users to Office 365 (OpenID Connect) authentication" does not work via cron job as expected. To confirm witness the following behaviour:

- create a user with Manual account (username the same as in Azure AD minus the UPN)
- run cron with matching enabled, no auth change
- match is successful according to cron output
- change settings to match and change auth type
- "User is already matched" reported in cron
- auth type remains as Manual account, Open ID Connect is not set as it should be

In cron we can see the user being matched but no auth switch takes place:

```
Syncing user user@domain.com
Found a user in Azure AD that seems to match a user in Moodle
moodle username: user, aad upn: user@domain.com
User is already matched.
```

**Comment by jamesmcq** [comment]
Hi @hcfhe-gshaw - Yes the the switch to OpenID Connect authentication will only take effect on the initial match - can you confirm whether, after you have switch authentication enabled, newly matches users have their authentication switched? At the moment switching after the fact using the user sync process is not supported.

**Comment by gunnar-restorff** [comment]
The auth method does NOT change even though the "Switch matched users to Office 365 (OpenID Connect) authentication" is chosen (on Moodle 3.3). What I do is either: 
1. I run the cron jobs so that all users in AD are matched
2. I note which users are not using OpenID
3. I go into Edit profile and change auth method

or 

1. I run the cron jobs so that all users in AD are matched
2. I make (somehow!) a comma separated file with all the matched users with the fields "username" and "auth" and set "auth" column to "oidc"
3. I upload the file using "upload users" (using appropriate settings such as update existing users etc...)

**Comment by nenorojas** [comment]
Hi, 

I'm closing this ticket due to inactivity, if it still happens on latest versions of Moodle, please let us know to reopen the case. 

Regards
