### ISSUE TITLE
Feature request: Allow viewing SharePoint files from Moodle without Microsoft login

### ISSUE THREAD

**Issue by amjohnson46** [microsoft/o365-moodle#1887]
We use SharePoint for distributing documents internally, but also need to distribute these same documents to people outside our organization. We would like to use Moodle to distribute externally, and only have to store the documents in one place. Would it be possible to set up a "Moodle user" in SharePoint, so that links to SharePoint documents in Moodle can be accessed without the Moodle user also having to log into SharePoint?

**Comment by weilai-irl** [comment]
Hi @amjohnson46,

At high level, I don't think what's required is achievable. 

If I understand it correctly, you want to make use of the feature to be able to map a Moodle user who's not using auth_oidc for authentication with an dummy Azure AD user, thus allowing the non-Azure Moodle user to access files in SharePoint as the dummy Azure AD user. The missing link here is the user mapping feature doesn't maintain a valid token for connected Azure Ad user, so that when the user tries to access a resource in SharePoint, the user will still be asked to login using the dummy Azure AD account details.

I hope this answers your question.

Regards,
Lai
