### ISSUE TITLE
Moodle Tab requires log in step

### ISSUE THREAD

**Issue by garradj** [microsoft/o365-moodle#1943]
Hello,

We are running Moodle 3.10 and the 3.10.5 plugins. After following the instructions and setting everything up, Moodle tabs are being created automatically in the Teams created via the custom course synchronization. All the plugin functionality seems to work properly. However, opening the Moodle tab requires an extra  login step to display the course page. Once that is completed the course page is displayed.

At this time we are not wanting to switch users to log in via Open ID connect. However, users have been matched mostly using the sync functionality and a few were matched manually in the sync settings. All users still log in via the original Moodle login method.

My understanding is that matched users belonging to the team should be able to open the Moodle tab and be authenticated automatically without logging into Moodle again. But I may be mistaken. I switched myself onto the Open ID Connect log in method to try, but this did not resolve the issue for me, the tab still required logging in so I switched the login method back again to just link my accounts.

I have read in some issues about checking the mdl_auth_oidc_token table for an issue, but I would need some guidance as I lack technical expertise and possibly would need to ask our server provider for assistance. We've tried reinstalling the plugins and Moodle app in Teams.

Any help would be greatly appreciated! Thank you.

**Comment by weilai-irl** [comment]
Hi @garradj,

I can confirm that the Teams SSO feature requires users to use auth_oidc authentication method for the SSO part to work. This is because of the way how SSO workflow is designed - it detects if there's a valid Microsoft 365 user session, and if one is found, it tries to use the token in it to login user; only auth_oidc users can login using the tokens, connected users using other authentication method cannot log in, simply because it would break the AUTHENTICATION process of the user's authentication method, i.e. the user is not actually authenticated according to how the other authentication method is designed.

At this stage I'm confident that the Teams SSO feature is working fine providing the setup is correct. If possible, please set up a new user, and test this in a new browser session (e.g. private mode), without any users logged in in either Moodle or Microsoft 365. If testing in a Teams desktop/mobile app, please log the user out first and log back in.

Regards,
Lai

**Comment by garradj** [comment]
Hi Lai, thank you very much for responding so quickly. I will try your suggestion.

If I'm understanding properly, matched users that are then moved to the auth_oidc authentication method should also be able to use the SSO part, is this correct?

When I moved my own account to the auth_oidc authentication method (I completed the connection and changed my login method through the Microsoft block), and used a new browser session, the browser tab did not authenticate me. Do you know why this could be? What would need to happen with existing users that have been matched through the plugin?

Thank you again your help!

**Comment by weilai-irl** [comment]
Hi @garradj,

Teams SSO should work for auth_oidc, regardless whether the account was converted to use auth_oidc from other authenticate methods, or created as such originally. Please check this part of the document to ensure the required configuration is in place https://docs.moodle.org/311/en/Microsoft_365#Moodle_and_Teams_SSO_integration. Normally Teams SSO issues are caused by incomplete setup.

Regards,
Lai

**Comment by garradj** [comment]
Hi Lai, and thank you again for your suggestions.

Unfortunately I'm still having trouble with the Moodle tab authentication. I did create a new user to set up with Open ID connect but the user was still not authenticated when accessing the Moodle tab. Again, on my own account that is using OpenID Connect to log in I also am not being authenticated on the tab. I also checked the documentation section linked above again and confirmed that each part was set up (I believe that this was set up by the initial Powershell script because nothing needed to be added or changed). I'm not sure what to look at next to try and find what isn't working. We have also now upgraded Moodle to 3.11 so now we are using the latest plugins 3.11.2 as well. Do you have a suggestion for what else I can check? 

I have also noticed that for some users during the user sync, the sync doesn't seem to properly match users against the Moodle email address as I had selected. Even after manually matching these users myself, those users still show as not being matched by the sync job log. Is that normal and will that cause problems for those users?

Thank you very much for your help!

**Comment by garradj** [comment]
Hello, @weilai-irl Can you confirm the expected flow for logging into the Moodle tab in a course team?
If I am understanding correctly, a synced user using Open ID connect for Moodle login should be able to open the Moodle tab without any login prompt and pass straight into the course page.
The only time a user should be prompted to login to the tab is if: 1) They are using manual login to Moodle, 2) If their Moodle session expires within the Teams tab? 3) If for some reason they had not logged into Moodle before?

My experience continues to be that I am presented the login buttons on the Moodle tab. I used the Teams mobile app (iPad) and added the account and logged in. When I open the Moodle tab, I am still presented with login buttons. When I click Microsoft 365, it does log me straight into Moodle afterwards. On the iPhone app, I actually had to login to the tab with Office credentials again. In a fresh web browser session with Teams, after logging in, the Moodle tab displayed the login buttons, but after clicking Microsoft 365 I was sent straight into the Moodle course page. But I am gathering this is not what should normally happen.

Thank you for your help!

**Comment by weilai-irl** [comment]
Hi @garradj,

Could you take a screenshot of the "Authentication", "Expose an API" and "App permissions" settings pages of the Azure app used for the integration please. I suspect this is caused by a missing step in the configuration setup.

Regards,
Lai

**Comment by garradj** [comment]
Hi @weilai-irl, I have emailed the screenshots to you. Many thanks for reviewing this.
