### ISSUE TITLE
Single logout from o365 not end moodle sessión

### ISSUE THREAD

**Issue by juandn** [microsoft/o365-moodle#2014]
When you sign out of an o365 app, such as Outlook, your o365 session ends successfully, but you can navigate in moodle.

The o365 logout page invokes 
"local/o365/sso_end.php?sid=xxxxxxx" and nothing happens.

Maybe this logout page is just for MSteams app embebed logout, if it is, what logout url should you set in the frontend logout url to log out of Moodle when you log out of o365.

Moodle 3.9
Latest STABLE_MOODLE39 plugin

**Comment by weilai-irl** [comment]
Hi @juandn,

I suppose you are using the the "Front-channel logout URL" in your Azure app setting and put "https://URL.TO.MOODLE/local/o365/sso_end.php" in the field?

<img width="752" alt="Screenshot 2022-03-25 at 16 10 22" src="https://user-images.githubusercontent.com/695310/160159141-b18bb4ca-fb7b-4778-a785-6ef01ffc5e6a.png">

If so, your understanding is correct that the script is only used to handle SSO request between Moodle and Teams in Teams SSO integration. Its purpose is not to log user out of Moodle.

Currently there's only one way Single Sign Out integration available from Moodle to Microsoft 365, which is configurable in the auth_oidc settings. The release version of the plugins don't support Single Sign Out from Microsoft 365 to Moodle. However, I did make a custom a solution for some of the clients that we support. It basically requires implementing a page similar to /login/logout.php, but without the requirement of sesskey, because Microsoft 365 would have no way to get the session key of the current Moodle session.

There is currently no plan to include this feature in the release, because any visit to the page will trigger an immediate Moodle user logout, without confirmation. It's probably undesirable in normal cases. But feel free to implement your custom solution if needed.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi all,

@mov-eax-eax, thank you for the hints. After some investigation, I confirm if the "Front-channel logout URL" is configured for the Azure app in the Azure portal, on user sign out from Azure, it will make a request to the configured URL with a "sid" parameter. The same "sid" was received in the login page too (in the "session_state" parameter), but currently it's simply ignored and not saved. We can extend the implementation of auth_oidc to support save it, so that it can be used to identify user before logging them out.

PS, I'll not post my custom solution to simply logout Moodle user without checking sesskey because it isn't the best practice and may cause unexpected issues.

@mov-eax-eax @juandn Since this is a potentially very useful feature, we will aim to have it implemented for the next release in before the end of July.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @mov-eax-eax @juandn,

The single sign out feature has been included in the latest release of the plugins from today. Please check it out and confirm if it works for you.

To highlight - you will need to set the "Front-channel logout URL" to be https://url.to.moodle/auth/oidc/logout.php for the feature to work.

I'll keep the issue open for another month and close it if no error is reported.

Regards,
Lai

**Comment by weilai-irl** [comment]
Closed one month after release.
