### ISSUE TITLE
Question: A way to suppress M365 group creation when a user creates Moodle group

### ISSUE THREAD

**Issue by geobuc1** [microsoft/o365-moodle#2031]
Hi,

Moodle Version: 3.9 , local_0365 integration: 3.9.0

I am just wondering if there is anyway to suppress the creating of an M365 group (and associated SharePoint site and welcome emails) when a user creates a Moodle 'group'?

I presume this is handled by usergroups\observers.php and triggers on the creation of such a group? Or would it be the case of going down the 0365 admin route trying to suppress the emails being sent out?  We sometimes have teachers creating Moodle groups, that they then don't want other users to see the other members, which they can't in Moodle , but the 365 welcome email and SharePoint site allows them to do this. 

I appreciate that as the course is Teams enabled , that there may be no way around this in the Integration?

Please accept my apologies if I have completely misunderstood the architecture.

Any thoughts or advice would be greatly appreciated. 

Kind Regards

**Comment by weilai-irl** [comment]
Hi @geobuc1,

I confirm that the feature to create Microsoft Group for each Moodle group created in a course configured to be connected to Teams is a legacy feature that was implemented long time ago when the Microsoft Group (not Teams) integration was first introduced. Microsoft Teams didn't even exist back then so the feature had some use at the time. However since the Moodle course and Microsoft integration provided by the plugins shifted focus to Teams, this feature doesn't fit its purpose any more. In fact, there are some issues with the current implementation even when it works - it doesn't create Microsoft Groups for existing Moodle course groups created before the course sync is enabled.

As a result, in the release that we made earlier this month (April 2022), the version of the plugins for Moodle 3.10/3.11 ([3.10.6](https://github.com/microsoft/o365-moodle/releases/tag/v20220411_m310) and [3.11.3](https://github.com/microsoft/o365-moodle/releases/tag/v20220411_m311)) removed the feature to create Microsoft Groups from Moodle course groups. It wasn't removed from the [release 3.9.9](https://github.com/microsoft/o365-moodle/releases/tag/v20220411_m39) for Moodle 3.9 though, because bug fix and feature support for the version has ended, and only security related support is available.

For the moment, I'm afraid you will need to local patches to remove this feature. While your proposal will work too, I think the easiest way may be to remove/comment out the observer definitions related to Moodle group and group member changes from `/local/o365/db/events.php`, i.e. lines at https://github.com/microsoft/o365-moodle/blob/7262e83b4a5a31b1cd4109eb0f59c392eafc4f14/local/o365/db/events.php#L29-L59.

The patch is required as long as you are on Moodle 3.9 versions of the plugins, and will not be required after upgrading to Moodle 3.10+.

Regards,
Lai

**Comment by geobuc1** [comment]
Hi Lai,

Firstly, thank you for your quick response, and secondly, for the detailed and clear information. This is really appreciated. 

So, to clarify, until we upgrade to 3.10/3.11 (3.10.6 and 3.11.3), the best way to stop the creation of 365 groups when Moodle groups are created is to remove\comment out (local\o365\db\events.php):

$observers = [
    // User groups
    [
        'eventname'   => '\core\event\group_created',
        'callback'    => '\local_o365\feature\usergroups\observers::handle_group_created',
        'priority'    => 200,
        'internal'    => false,
    ],
    [
        'eventname'   => '\core\event\group_deleted',
        'callback'    => '\local_o365\feature\usergroups\observers::handle_group_deleted',
        'priority'    => 200,
        'internal'    => false,
    ],
    [
        'eventname'   => '\core\event\group_updated',
        'callback'    => '\local_o365\feature\usergroups\observers::handle_group_updated',
        'priority'    => 200,
        'internal'    => false,
    ],
    [
        'eventname'   => '\core\event\group_member_added',
        'callback'    => '\local_o365\feature\usergroups\observers::handle_group_member_added',
        'priority'    => 200,
        'internal'    => false,
    ],
    [
        'eventname'   => '\core\event\group_member_removed',
        'callback'    => '\local_o365\feature\usergroups\observers::handle_group_member_removed',
        'priority'    => 200,
        'internal'    => false,
    ],

Notwithstanding any other modifications we may have made , this should cause no issue in connection to 'Moodle to Teams' creation\sync etc.?

Again, I must apologize as our admin who dealt with this has left and I am trying to get a handle on things. 

Thanks again for your assistance.

**Comment by weilai-irl** [comment]
Hi @geobuc1,

That is correct. I confirm commenting out the lines will effectively disable the feature to create Microsoft Groups from Moodle course groups. There is not consequences that I can see with this approach.

Regards,
Lai

**Comment by geobuc1** [comment]
Hi Lai,

Thank you for you confirmation. I will try this approach.

Thank you again for your help in this matter.

**Comment by geobuc1** [comment]
Hi Lai,

I have commented out the following lines in local\o365\db\events.php. However, Microsoft Group from Moodle course Group was still created (email received and SharePoint site created). Have I missed something? Is there anywhere else, that you are aware, I need to look or comment out?  Again, thanks for your help in this matter. 

$observers = [
    // User groups 
	
    /*[
        'eventname'   => '\core\event\group_created',
        'callback'    => '\local_o365\feature\usergroups\observers::handle_group_created',
        'priority'    => 200,
        'internal'    => false,
    ],
    [
        'eventname'   => '\core\event\group_deleted',
        'callback'    => '\local_o365\feature\usergroups\observers::handle_group_deleted',
        'priority'    => 200,
        'internal'    => false,
    ],
    [
        'eventname'   => '\core\event\group_updated',
        'callback'    => '\local_o365\feature\usergroups\observers::handle_group_updated',
        'priority'    => 200,
        'internal'    => false,
    ],
    [
        'eventname'   => '\core\event\group_member_added',
        'callback'    => '\local_o365\feature\usergroups\observers::handle_group_member_added',
        'priority'    => 200,
        'internal'    => false,
    ],
    [
        'eventname'   => '\core\event\group_member_removed',
        'callback'    => '\local_o365\feature\usergroups\observers::handle_group_member_removed',
        'priority'    => 200,
        'internal'    => false,
    ],*/

**Comment by weilai-irl** [comment]
Hi @geobuc1,

I think I might have missed a point in my last proposal - after you comment out the observer definitions, you will need to bump up the version of the local_o365 plugin to allow it to take effect. Moodle caches observers when plugins are updated, so this step is necessary. If you just bump version by 1 (to the last digit), it normally won't affect future upgrades, as the plugin version are incremented by more than 1 in official releases.

Please give it a try and see if it works.

Regards,
Lai

**Comment by geobuc1** [comment]
Hi Lai,

Thank you. I purged all caches in Moodle and this seemed to have the desired effect? Tested with user and Microsoft Group from Moodle course Group seems to have ceased. For clarity, when you say bump up version of local_0365 plugin you mean in:

local\o365\version.php:

$plugin->version = 2020071500;
$plugin->requires = 2020061500;
$plugin->release = '3.9.0';

Sorry if I have misunderstood. Thank you for all your help and support with this.

Regards

George
