### ISSUE TITLE
MS Teams intergration error creating a classrom based Team.

### ISSUE THREAD

**Issue by Lwanda-SIfolo** [microsoft/o365-moodle#2114]
I getting erros from intergration  creating Teams based on a classroom template.

The was an option, to choose the creation of a team based on a classroom. with the new plugin update the option no longer the.

**Error on logs**

......... Could not create class team from education group. Reason: Error in API call: Failed to execute Templates backend request CreateTeamFromGroupWithTemplateRequest. Request Url: https://teams.microsoft.com/fabric/emea/templates/api/groups/330a0733-059d-4d91-bcf7-3743a9f61651/team, Request Method: PUT, Response Status Code: BadRequest, Response Headers: Strict-Transport-Security: max-age=2592000
x-operationid: 65a8b814c55c6e43851dcf72f1ab85e3
x-telemetryid: 00-65a8b814c55c6e43851dcf72f1ab85e3-23a01c3472ca7348-00
X-MSEdge-Ref: Ref A: 519CC6338A5D4FF4905BDC2EF8F8B710 Ref B: PRAEDGE0805 Ref C: 2022-08-10T07:18:11Z
Date: Wed, 10 Aug 2022 07:18:11 GMT
, ErrorMessage : {&quot;errors&quot;:[{&quot;message&quot;:&quot;Team with template 'educationClass' can not be provisioned using a group which does not belong to a class.&quot;,&quot;errorCode&quot;:&quot;Unknown&quot;}],&quot;operationId&quot;:&quot;65a8b814c55c6e43851dcf72f1ab85e3&quot;}
......... Failed to create class team from education group with ID 330a0733-059d-4d91-bcf7-3743a9f61651 for course #11650

**Comment by weilai-irl** [comment]
Hi @Lwanda-SIfolo, 

Thank you for reporting the issue.

I confirm the option was removed on purpose. According to the Teams integration guideline provided by the Microsoft Education team, it was required that all users who have tenants with education licenses should only use Class Teams, and standard Teams should only be used by users whose tenant don't have education licenses. The plugin has a logic to determine if the tenant has education licenses, and the option is obsolete, therefore removed.

After the change, if you have education license, your group will be created using [Create educationClass API](https://docs.microsoft.com/en-us/graph/api/educationroot-post-classes?view=graph-rest-beta&tabs=http), and you will be able to create a Team using the Class template from the group.

The error message in your reporting suggests that your group was not created by the Create educationClass API, therefore isn't treated as an education class. Trying to create a class Team from a standard a group would result in the error.

The most probable reason was the group was created before plugin upgrade. Could you confirm please.

To solve the issue, the most straightforward approach is to delete the group created, and let the scheduled task to create the group/team again, using the new Graph APIs. You can do this by running the following SQL query:
`DETELE FROM mdl_local_o365_objects WHERE type = 'group' AND moodleid = COURSE_ID;`

If you can't unlink the course with the existing group for some reason, e.g. there are already activities in the group and you don't want to use them, the only option you have is to "hack" the plugin to let it create standard team instead of a Class team. You can do this by hacking the function that checks if the tenant has education license (has_education_license() in /local/o365/classes/rest/unified.php).

Regards,
Lai

**Comment by Lwanda-SIfolo** [comment]
@weilai-irl Thank you.

we took the first option.

For the benefit of others, different object creation between the new and the old plugin.

Old plugin;

![image](https://user-images.githubusercontent.com/66300421/185141873-1db2cabb-91a7-42a7-8e33-d89b4afc09ba.png)

Newly updated plugin.

![image](https://user-images.githubusercontent.com/66300421/185141530-587514da-ac72-4ed5-adaf-2aac98cf48c0.png)
