### ISSUE TITLE
User creation from auth_oidc ignores the Moodle "Allow accounts with same email" setting

### ISSUE THREAD

**Issue by tim1mw** [microsoft/o365-moodle#2185]
Moodle has a setting "Allow accounts with same email" (allowaccountssameemail) which defaults to No and exists to prevent more than one account being created with the same email address. auth/oidc does not obey this setting and will push duplicate email addresses into the Moodle database when creating new accounts. 

The attached patch adds a check to the account creation process which will check if the email address of a new user already exists in the Moodle database. Ideally syncing in of duplicates should also be blocked, but I don't have a patch for that yet.

[dup-email-patch.txt](https://github.com/microsoft/o365-moodle/files/9628065/dup-email-patch.txt)

**Comment by weilai-irl** [comment]
Hi @tim1mw,

Thank you for reporting the issue and providing the patch. I'll review the changes and integrate it in the upcoming releases.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @tim1mw

I have tested your patch and it works perfectly. I have created a PR based on it and it will be included in the next release.

I have reviewed similar situation in the user sync task, and I confirm a similar change is not required. When running the user sync task, if a Moodle account is found matching the email address of a unconnected Microsoft account, the task will try to process it according to the "Match preexisting Moodle users with same-named accounts in Azure AD" user sync option, rather than trying to create a new Moodle account. There is a related issue in this process and I have reported it at #2222, and a solution will be provided in the same release as the fix to this one.

Thank you again for reporting the issue and providing the solution.

Regards,
Lai

**Comment by tim1mw** [comment]
That's great news, thankyou.

**Comment by weilai-irl** [comment]
Hi @tim1mw 

The fix you provided included in the release from today ([3.11.6](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m311), [4.0.3](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m400) and [4.1.1](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m410)) following review and test. I'll mark this issue closed.

Thank you again for reporting the issue and providing the fix.

Regards,
Lai
