### ISSUE TITLE
Misspelt Label in auth/oidc settings.php

### ISSUE THREAD

**Issue by miraclechris** [microsoft/o365-moodle#2191]
On June 9th a commit:22613068fb8590c05c5f0cc30da9848ba943d238  was introduced which has a misspelt label at line 212 of auth/oidc/settings.php. It has named the label "cleaniodctokens":

 $settings->add(new auth_oidc_admin_setting_label('auth_oidc/cleaniodctokens', get_string('cfg_tools', 'auth_oidc')
 
 The setting should name the label "cleanoidctokens":
 
$settings->add(new auth_oidc_admin_setting_label('auth_oidc/cleanoidctokens', get_string('cfg_tools', 'auth_oidc')

Chris

**Comment by weilai-irl** [comment]
Hi @miraclechris 

Thank you for reporting the issue.

I confirm the change has been overwritten again for Moodle 3.11/4.0 version of the plugin in the 3.11.5 and 4.0.2 releases of the plugin from October 2022. The typo is still in 3.9 and 3.10 versions, but since they out of bug fix support and this is doesn't affect user interface, they can be left as is.

I'll close the issue.

Regards,
Lai
