### ISSUE TITLE
Accidentally changed auth_oidc clientid

### ISSUE THREAD

**Issue by kinnectus** [microsoft/o365-moodle#2198]
Our Moodle host accidentally overwrote "clientid" in "auth_oidc". They didn't realise when they went to configure a new environment it had redirected them to our production environment because reply URLs had not been provisioned in our Azure tenancy for the new environment.

Needless to say, this cleared all our user tokens and objects in Moodle.

We reverted the "clientid", saved and, within a few minutes, users were able to sign in again.

We have noticed, however, that no "user" objects are being created in mdl_local_o365_objects, nor can we see any entries in mdl_local_o365_connections.

We don't use the sync tasks or have the sync tickboxes ticked because we don't want Moodle matching users automatically. We have users sign in via a forced redirect to the M365 sign-in page and then user is then redirected back to Moodle and they are signed in. The user accounts are of type "OpenID Connect".

We are confused as to why when we get to sign a new user in they aren't getting on m an object created in mdl_local_o365_objects table, where this previously worked.

Is it possible that when our host reverted the clientid that we MUST click the "Grant admin consent" button from within Moodle? When we click the "Update" button on stage 3 it says everything is alright, but it's actually not.

Any advice? Thank you!

**Comment by weilai-irl** [comment]
Hi @kinnectus,

If the site is using the latest release from October 2022 (release 4.0.2/3.11.5), Azure admin will need to provide admin consent again from Moodle. If using other versions, they will not be required to do it.

When **clientid** is updated, the application token is always deleted, regardless of plugin version. The next time the verify setup button is clicked, it will try to get a new application token, which in theory should contain the same claim as the previous one. So from my understanding it should work.

Regarding the records in **local_o365_objects** and **local_o365_connections** tables:

- **local_o365_connections** table contains manual connections, and the only two ways to add them is (1) for site admins to update them using CSV files, and (2) if given the capability, users can connect themselves from block_microsoft. Otherwise the table will remain empty.
- User connection records in the **local_o365_objects** table are added by an observer function in the local_o365 plugin that listens for auth_oidc\event\user_connected events. You can check in the standard log to see whether the events are triggered on login. It should be triggered when adding saving user tokens to the **auth_oidc_token** table for the first time after it was cleared down due to the **clientid** change.

Just think out of the box, while the ultimate goal is to restore the deleted records, is there a possibility to restore deleted records from a backup?

Regards,
Lai

**Comment by kinnectus** [comment]
Ideally we'd restore from a backup of the table, however we're still not really sure how it's actually stopped working. Why are new objects not being created? We have just started a new academic year and we have hundreds of new students, many of which will be logging in to Moodle for the very first time even today (after the incident).

We have a fairly normal install - we don't make use of the plugin's ability to sync to Azure, as I said earlier - and it has worked well prior to the incident where our provider changed our clientid. User objects were being populated into the table after they logged in for the first time. Microosft Teams groups were being populated. It was actually us using the custom Teams option to create a Teams group from a course that we understood what was going on - the Teams group scheduled task was not creating the group because there was no owner (yet there was). This led us to look in the objects table.

We currnetly us v3.11.4 version of the plugin.

**Would you think it worth us clicking the "Provide Admin Consent" button again, even though we don't use v3.11.5? Our Moodle host wouldn't have the permissions to our Azure to be able to do that, so we assume they simply re-entered the clientid and clicked save at the very bottom of the setup page.**

Thank you for your very prompt response.

**Comment by kinnectus** [comment]
OK, so we're no further forward with this.

We performed the same steps to reproduce the issue, this time on our UAT environment. This time we clicked the "Provide Admin Consent" button in Moodle and got one of our global admins to provide the necessary consent. However, still the problem exists.

Users can log in, but no "user" objects are created in "local_o365_cobjects" table.

We created an event monitoring rule and subscribed to it. We logged a few users in. No events were triggered.

As I've previously stated, we don't use the Moodle/Azure sync. We have no intention of doing so because our users are either pushed in to Moodle and then sign in, or they sign in of their own accord. Ours users sign in via the redirect to the Azure SSO page. So: they hit our Moodle URL -> They get redirected to Azure SSO if they are not already signed in -> They sign in and get redirected to Moodle. This has worked for us forever. Obviously we've never just changed the "clientid" by choice - it's always been set-and-forget. The only piece we've had to change is the client secret when it expired.

Prior to this issue we were successfully getting users have "user" objects in "local_o365_objects" table. Users were able to be successfully added as Teams group members when using the Teams integration.

At the moment no new user objects are being created. We just don't understand this.

**Comment by mmulrthelp** [comment]
Hi @kinnectus whilst you wait for a reply from Lai, I was wondering if you have tried to clean the user tokens by deleting the old delta sync token?

You do this here : <your moodle site>/local/o365/acp.php?mode=maintenance
"Cleanup User Sync Delta Tokens"

This forces a complete re-sync the next time when the user sync is run.. This and the 'Admin Consent' has solved issues on our installation in the past. I'm not 100% convinced it will help you solve it for you as you do not use the 'Sync users with Azure AD' schedule task.

There may also be another maintenance tool on the above page which will help you out for just the Teams issue which you are seeing.

Regards,
Ray.

**Comment by kinnectus** [comment]
Hi Ray,

Thank you for this. Unfortunately we're now experiencing the issue on a completely fresh Moodle 3.11.

We installed Moodle with auth_oidc and local_o365 plugins. We ran the PowerShell script and it created the app registration. We enabled OpenID Connect authentication plugin in "manage authentication methods". We signed in as an o365 user. We successfully logged in and saw that a token in Auth tokens table was created. We checked the "Manage user connections* in 365 local plug-in page. The user was "Connected". But no user object created in objects table. It's fairly apparent that this process is not triggering the required event to call the observer function that creates the object.

**Comment by weilai-irl** [comment]
Hi @kinnectus,

After an internal call with @nenorojas and some investigation, I confirm there was indeed a bug in the local_o365 plugin which doesn't create connection records in local_o365_objects table for users using auth_oidc on their login. The bug was introduced in release 3.11.3.

A solution has been provided in the linked PR. Upon testing, it will be included in the next release.

Regards,
Lai

**Comment by kinnectus** [comment]
Hi Lai,

We successfully tested the 311 PR on a vanilla Moodle install. We tested the following scenarios:

1. An existing user where their local_o365_objects record had been deleted but was not being recreated. **Success**: a new record was created for the user. We extended the testing to delete the object and sign the user back in again. A new record was created.
2. A non-existing user signing in for the first time. **Success**: a record was created for the user
3. Deleting a user through standard Moodle users page. **Success**: signing the user back in again created a new profile and created a new user object

**Comment by weilai-irl** [comment]
Hi @kinnectus 

The fix to the reported issue has been included in the release from today ([3.11.6](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m311), [4.0.3](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m400) and [4.1.1](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m410)). I'll mark this issue closed.

Feel free to reopen if the fix doesn't work for you.

Regards,
Lai
