### ISSUE TITLE
Moodle username does not sync with 365 username without tenant

### ISSUE THREAD

**Issue by AmarJaved** [microsoft/o365-moodle#224]
Reading the documentation the accounts should sync so that "test@email.com" in 365 should sync with username "test" in moodle, however when I access moodle through 365 a new account is created with "test@email.com" as username.

I deleted both accounts and tried this again, but changed "test" to "test@email.com" in moodle, the auto sync worked, however I do not want to use the full email as the username.

I have re read the manual and can't see what I am doing wrong or if this is a bug?

I am using Office 365 plugin ver 3.1.0.5 and Moodle 3.1.1

**Comment by upats** [comment]
I am having this same issue with a subset of users in Moodle. I thought I had figured it out--there is a discrepancy between some of the mdl_local_o365_xxxxxxx tables in the database with users that are in some of those but not in others. 

For example, test@email.com exists in mdl_local_o365_connections but not in mdl_local_o365_objects. It seems that users need to be in both tables in order to log in properly but the sync job will not create new o365_objects if they are already in the o365_connections table. What I did was purge out all entries in o365_connections that did not exist in o365_objects and re-ran the sync script. The sync script then successfully created o_365 object entries for the users. 

I thought this fixed the issue but now the newly synchd users who log in have the same issue as @AmarJaved reported: when they log in a new "test@email.com" username is created (that has no moodle data associated with it, of course, since it's a new user) instead of logging them in as the existing username "test."

I now see there's another table mdl_local_o365_appassign that has discrepancies in it as well. I'm currently trying to see if I can manipulate this table to prevent the oidc plugin from creating new users.

The last approach I can think of is just clearing out all three of the o365_connections, o365_objects (just user objects), and o365_appassign tables and re-synching all users. Not sure if I want to use this nuclear approach since it most likely will break calendar syncs and activities in courses :(

**Comment by giselebrugger** [comment]
1040/5000
what I noticed in my integration with office 365 (with the existing user accounts in Moodle) was:

The moodle username must always be the full login name (including the domain)

For example:

if user (username) moodle = jose.silva (with auth manual or email for example)

and login office is jose.silva@student.myuniversity.com

I have to do the following before running the match:


1) change the user's username in Moodle to jose.silva@student.myuniversity.com
keeping the authentication field as manual or email for example

2) run the match through the User Matching tool ../in moodle / admin / settings.php? Section = local_o365 & s_local_o365_tabs = 2

with the .csv file

jose.silva@student.myuniversity.com, jose.silva@student.myuniversity.com, 1

only after these procedures did not create a new account for the user in moodle.

After executing the math the user authentication is changed to: openid connect and connection status user in ../moodle//local/o365/acp.php?mode=userconnections is:

Synced from Azure AD.
Awaiting initial login.



I think this happens because azure has several domains:

examples:

xx@student.myuniversity.com.br
xx@teacher.myuniversity.com.br

**Comment by AmarJaved** [comment]
I have now come up with an alternative solution to my issue.

I am updating the user table via SQL to do the following,
1. Update all username to username + tenant if it doesn't have one already
2. Amend all auth to oidc

One of the problem I was trying to resolve was that I wanted to avoid adding the tenant at the end of the username so the end user doesn't have to keep adding the tenant when they login, however with open id the user just needs to click on the open id icon and then log in office 365 (if not already logged in). 

As part of the change I am also disabling all authentication except open id and manual, so it is only possible to log in with office 365 and this avoids account duplicating.

upats - I wouldn't recommend deleting the local_o365 tables as this will not prevent duplicate accounts being created.

If you have any questions feel free to contact me.

**Comment by halvarezast** [comment]
Could you help me with this problem? 
I haven't been able to solve the problem. 
Thank you!

**Comment by AmarJaved** [comment]
@halvarezast
What have you done so far? and What are you trying to achieve?

**Comment by halvarezast** [comment]
I have installed Moodle 3.7 and before I had Installed Moodle 3.6. However I have not been able to achieve user synchronization. Then, I need to restart the server through VHM, and after that, I run the Moodle Cron (http://examplemoodle.edu.co/admin/cron.php) I was able to synchronize only 58 users. 
To increase users number I need to repeat the process.  By the way, In CPANEL I have cofigured the cron task ( cd '/home/example/public_html/examplemoodle/admin/cli/' ; php -q 'cron.php' > /dev/null ; )

Could you help me? please.

**Comment by AmarJaved** [comment]
I don't think I can provide much help here.

On my environment I never needed to sync the user data through cron.php as the data would automatically sync when the user attempts to login. Once I changed the username test to test@email.com, the next time test logs in through office365 the plugin would look for test@email.com and sync the office365 to the moodle login (the moodle login was changed to openid otherwise the sync wouldn't work).

One other thing is that a very small number of users wouldn't sync correctly (50 users out of 1000), even though their account existed in moodle, when they login through office365 it would create another account with the exact username. To resolve these account, I manually copied the copied the data from old to new account and deleted the old account.

**Comment by cb526** [comment]
Was anyone able to resolve this issue without changing the Moodle usernames? I have come across this issue in Moodle 3.6 though I didn't have it when testing with Moodle 3.4.

**Comment by AmarJaved** [comment]
@cb526, I wasn't able to find a way, the easiest solution was to change the username via SQL and then everything else worked.

**Comment by cb526** [comment]
Thank you @AmarJaved

**Comment by nenorojas** [comment]
Hi,

I'm closing this case due to inactivity, Please try the latest version of the plugin with latest version of Moodle, if it's still an issue. Please raise a new request.

Regards
