### ISSUE TITLE
Calendar Appointments Not Updated/Deleted

### ISSUE THREAD

**Issue by danielmitchell** [Microsoft/o365-moodle#225]
Calendar syncing has been enabled in both directions and creating new appointments in either Moodle or Outlook automatically syncs to the other system.

Subsequently updating or deleting an appointment in Outlook does not get synced to Moodle and the original details remain; the opposite works correctly and updating an appointment in Moodle gets synced to Outlook. Reviewing the scheduled task code in local/o365/classes/feature/calsync/task/importfromoutlook.php suggests that only new appointments are created and there are no updates or deletes performed.

Is this on the roadmap to be fixed in a future release?

**Comment by nimojg-microsoft** [comment]
@danielmitchell  Have you tested the latest release? Are you still seeing this issue?

**Comment by jamesmcq** [comment]
@danielmitchell The file you mentioned does indeed only deal with creating new events because updates and deletions are handled elsewhere - this file is just a task for bulk importing events during initial sync. Can you provide any more information on what might be going on? Check out the [troubleshooting](https://github.com/Microsoft/o365-moodle/blob/master/Office365Documentation.md#troubleshooting) guide for some tips on debugging and any additional information that might be helpful.

I'm going to close this issue for now just due to age, but please feel free to re-open or submit a new issue with any additional information you might be able to provide. Thanks!

**Comment by MadsReese** [comment]
I have the same issue as @danielmitchell, I can see that the Troubleshooting link leads to a 404, is there another place to look for troubleshooting steps?

Regards
