### ISSUE TITLE
JWTmalformed error after upgrading from 3.10 to 3.11

### ISSUE THREAD

**Issue by JKaplan65** [microsoft/o365-moodle#2251]
Hi team, and thanks for this **great** plugin

My moodle instance with openid plugin is connected to openID IdP based on ORY (Kratos, Hydra, Keto). Was working fine, but I recently upgraded from 3.9.10 (or 3.9.11, not sure) to 4.1.0. Now, I get the JWT malformed error systematically
I checked one JWT returned by my IdP into http://jwt.io and it seems fine (encoding HS256)

Could you help please ?
Thanks in advance

**Comment by JKaplan65** [comment]
Hi team
I continued investigations and narrowed down the plugin version that breaks my IdP interface.
Working fine with openid plugin 3.10, ko with 3.11
We had a look at code changes but they are HUGE and need plugin experts to determine the root cause of this problem. Could you help please ?

**Comment by adamzammit** [comment]
I am seeing this error too after upgrading to Moodle 4 / plugin version 4.1.0 from Moodle 3 / plugin version 3.10

**Comment by adamzammit** [comment]
If I replace: 

https://github.com/microsoft/o365-moodle/blob/master/auth/oidc/classes/loginflow/base.php#L214

with:

`$tokenames = ['idtoken'];`

i.e. remove 'token' from the array so it doesn't iterate over it - then auth works again for me (using cilogon)

**Comment by JKaplan65** [comment]
Hi Adam

thanks a lot for the tip - unfortunately, this does not solve the JWT error in my configuration. I am connected to 3rd party idp
any other idea on how to investigate on this ?

**Comment by adamzammit** [comment]
I added this code:

$e = new \Exception;
var_dump($e->getTraceAsString());

Right before this line:

https://github.com/microsoft/o365-moodle/blob/master/auth/oidc/classes/jwt.php#L56

To get a stack trace of what was going on during the auth process.

Please note that this will expose tokens to the browser so only use it for testing.

**Comment by weilai-irl** [comment]
Hi @JKaplan65 and @adamzammit 

I think the root cause of this issue is improper error handling when checking tokens, along with differences in tokens from different IdPs. Most of tests that we performed before release are on Azure AD, and the issue didn't happen in our tests. It looks like different IdPs sends different tokens, and the function to decode them should be able to tolerate errors in decoding them.

I have included a fix to the issue in the release from today ([3.11.6](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m311), [4.0.3](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m400) and [4.1.1](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m410)). Please check it out and confirm if it fixes the error.

I'll mark this issue closed, but feel free to reopen if the fix doesn't work for you.

Regards,
Lai

**Comment by JKaplan65** [comment]
Hi @weilai-irl

I confirm this fixes my problem (with 4.1.1) !
This is really great news for us, we will be able to open our platform and begin teaching for our 40.000 people association working for the adaptation to climate change ! 
A very big *thank you* for your time and talent, and I wish you all the best

Frederic

**Comment by adamzammit** [comment]
Thank you for your great work @weilai-irl 

I can confirm this has resolved it on my installation also.

Adam
