### ISSUE TITLE
User sync does not work after update 2022112805

### ISSUE THREAD

**Issue by andresmelot** [microsoft/o365-moodle#2335]
Hi, 

The user sync is not workign after updating from 2022041910 to 2022112805, local_o365 plugin get misconfigured after the update process, the message` "...... Microsoft 365 not configured"` is displayed when the user tries to run the task `"\local_o365\task\usersync"`. After some research we found the sync process works again if you press the "Save changes" button on OIDC's settings page(`/admin/settings.php?section=authsettingoidc`) and you click "Update" button on local_o365's settings page(`/admin/settings.php?section=local_o365&s_local_o365_tabs=0`).

**Steps to replicate:**

- Update from from 2022041910 to 2022112805
- Run the task \local_o365\task\usersync
- Check the result
    - "...... Microsoft 365 not configured" message is displayed
- Navigate to OIDC's settings page
- Press "Save changes" button
- Navigate to local_o365's settings page
- Press "Update" button
- Run the task \local_o365\task\usersync
- Check the user sync task is working again

**Comment by weilai-irl** [comment]
Hi @andresmelot 

Thank you for reporting this. I confirm the behaviour is expected. Release 4.0.3 from September 2022 introduced the support of Microsoft Identity Platform, on top of Azure AD, i.e. oauth2 2.0 vs 1.0. There were extensive changes in the new version, and while there are some common concepts, technology, and settings used, many others have changed. In particular, the authorize and token endpoints are different, and the steps to get application token have also changed.

The configuration pages were updated to accommodate such changes, and as part of the changes, additional checks were added to ensure the integration configurations are correct. When some of the configurations are incorrect, the named errors would be shown, and site admins would need to update the configurations and verify them again. This is exactly what happened in your case.

Since the user sync tasks are back working again after configuration update, I'm going to close this issue.

Regards,
Lai
