### ISSUE TITLE
Full sync database error

### ISSUE THREAD

**Issue by todog** [microsoft/o365-moodle#2339]
Hi 

In [#1741](https://github.com/microsoft/o365-moodle/issues/1741) a full user sync results in an error using Microsoft 365 Integration 3.9.6 with Moodle 3.9.3

This was fixed by [#1742](https://github.com/microsoft/o365-moodle/pull/1742)

However the same error is now occurring using version 4.1.1 of the plugin with Moodle 4.1.3

Will be grateful for any assistance in the getting the full sync working.

**Comment by todog** [comment]
There is a work around, probably only relevant to installs with MSSQL, change the default number of users that are sync'd from 1000 to 500 in usersync.php at o365\classes\task\

**Comment by weilai-irl** [comment]
Hi @todog 

I'm glad to hear that you have found a solution.

This may have to do with maximum number of parameters allowed in your database configuration. We use MySQL for most of development and testing; we also have sites running with PostgreSQL, which behave differently in some database queries. We currently don't have sites running on MS SQL DB servers, but our experience is even using the same DB, configuration difference may result in different outcomes too.

Since you have found a way to solve the issue, I'd suggest you keep a local patch with the fix. I'll close the issue in that case.

Thank you again for reporting the issue.

Regards,
Lai
