### ISSUE TITLE
Auth OIDC: Possibility of using Client Certificate Path at IdP and authentication

### ISSUE THREAD

**Issue by joaop221** [microsoft/o365-moodle#2378]
Greetings,

With actual config of Idp auth requires that user inputs raw certificate contents (including private key). Moodle grants security of this approach, but some organizations require that some of such contents are placed at key vault solution or file path (inclusive key vault can do this). Searching the contributions available here, I've found this implementation #2235 and the discussion about overcomplication that this implementation implies.

So I've been thinking about the possibility of specifying a default location of certificates inside **IdP and authentication** feature, giving admin option to describe both filenames (public and private key) that will be placed at this _"default location"_. Of course, cert passphrase will be appreciated.

If these ideas are viable for this project, I'm at your disposal. (Some of the work is already done - PR will come soon).

**Comment by joaop221** [comment]
@weilai-irl is this feature viable?

I'd like to know if there is any process or implementation to make it possible.

**Comment by yabbondanza** [comment]
It would be really great if we have a feature like this.

**Comment by gabiaabreu** [comment]
That would be a nice and useful feature to get implemented. Any updates on this?

**Comment by frankgalindo** [comment]
Up!

I would appreciate this feature!

**Comment by weilai-irl** [comment]
Hi @joaop221 

Sorry for not getting back to you sooner.

Yes, I think this feature is viable. I'll review your implementation and aim to include it in the next release.

Regards,
Lai

**Comment by joaop221** [comment]
Hi @weilai-irl, 

During tests and reviews of this implementation, I've found some problems with client objects (local_o365) that interact with authentication methods (auth_oidc) when Certificate authentication method is used. Follow the list:

- Cannot reload token for user profile photo update;
- Warning during cron executions.

I believe this happens because of static method that does not verify authentication method and create an object using client secret. See below:

https://github.com/microsoft/o365-moodle/blob/f796d9dfc27fdede24225cbc1ce445fb417fc1cb/local/o365/classes/oauth2/clientdata.php#L117C12-L117C12

I'm working on finding the solution for this problem, but any changes to this method will cause multiple changes to all graph API calls.

**Comment by weilai-irl** [comment]
Hi @joaop221,

I have reviewed your PRs and they look very good to me. They work as expected on certificates configured in file names, and for those encrypted using passphrase.

I made some small changes and created separate branches and PRs in order to comply with our release process. The changes I made are:
 - Apply passphrase logic to "Plain text" certificate source.
 - Initialise "Certificate source" configuration during upgrade.
 - Set default value for the "Certificate source" configuration in case it's missing.
 - Change the base location where certificate files are stored.
 - Update some language strings.

I'll include this item in the pre-release test in our process, so that they can be included in the next release.

FYI, support for Moodle 4.0 version of the plugin has been dropped, so this feature will not be supported in 4.0 version.

Thank you again for your contribution. I'll review other issue mentions in your latest comment separately. 

Regards,
Lai
