### ISSUE TITLE
Issue with Moodle 4.3

### ISSUE THREAD

**Issue by nbozhkov-ucl** [microsoft/o365-moodle#2384]
We have been testing the upgrade from Moodle 4.2.2 to Moodle 4.3beta to spot early problems & get fixes before 4.3 official release. After we upgraded succefully, AAD authentication no longer works coming up with the below error message.

Exception - update_internal_user_password(): Argument #2 ($password) must be of type string, null given, called in [dirroot]/lib/moodlelib.php on line 4484

**Comment by weilai-irl** [comment]
Hi @nbozhkov-ucl 

Thank you for reporting the issue. We haven't started testing the plugins on Moodle 4.3 yet since it hasn't been released. Official support for new Moodle versions are normally added within one month after the release. We have a full set of test cases to run so this may take some time. I'll add the issue reported to the list of items to fix for Moodle 4.3 release.

Regards,
Lai

**Comment by weilai-irl** [comment]
@nbozhkov-ucl, @opitz

Thank you for reporting and issue and providing solution. The latest release of the plugins from today (v4.3.1, https://moodle.org/plugins/auth_oidc/4.3.0/30700) should fix this one. Please check it out.

Regards,
Lai
