### ISSUE TITLE
Moodlesession timeout in Teams

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#2388]
Hi

when you are using a Moodle course in Teams tab, and Moodle session is timeouts, after re-login you are brought to Moodle frontpage, not the original course. 

Is it possible to bring user to the correct course after login in that situation?

**Comment by weilai-irl** [comment]
Hi @kkiiskin

I understand the requirement and have been trying to find a solution, but so far I found no luck.

The main issue is, when a user clicks the Moodle tab in Teams to launch the Moodle tab, a request is made to a custom script in the local_o365 plugin, e.g. https://url.to.moodle/local/o365/teams_tab.php?id=COURSE_ID; the page will try to login the user using SSO, and upon successful login, the user will be redirected to the course view page. After it, it would be the exact same as opening a Moodle page in a browser, the only difference is in this case, the "browser" is a Teams tab, which is technically an iframe. With that said, Moodle doesn't know the context in which its page is opened. When the user session times out, Moodle also doesn't have a clue whether it's opened in a Teams app or not, therefore it's the same as when a user session times out in a normal browser. Depending on which link the clicks to triggered the redirect to the login page, Moodle will sets the "wantsurl" in the session. Note since the user has been logged out, this would be a different session as the previous one when the user is logged out. Upon successful login, the user will be redirected to this "wantsurl".

If you configure the integration to use the custom theme_boost_o365teams theme in Teams, it would remove most obvious links to other parts of the Moodle site, including the home/dashboard page, so users will have the most chance to have the course view page, or another page within in the course, in the "wantsurl" parameter, so that they will be redirected back to the course after login.

I'm afraid this would be the most that we can achieve. Please let me know if you have other ideas.

Regards,
Lai
