### ISSUE TITLE
Moodle with Multi Factor Authentication office365

### ISSUE THREAD

**Issue by pedroalpacheco** [Microsoft/o365-moodle#242]
Hi all, 

Does anyone already use office365 with Multi Factor Authentication  in moodle?

Users with Multi Factor Authentication can not log in to moodle.

Has anyone ever had this problem?

**Comment by jamesmcq** [comment]
@pedroalpacheco Do you have any more information to share? What happens when users try to log in? Do you experience this with any other SSO-type auth plugin?

**Comment by pedroalpacheco** [comment]
Hello @jamesmcq
In our moodle, version Moodle 3.1.11 (Build: 20180319), we use authentication via plugin Office 365, authentication is performed without problems, only users who choose Multi Factor Authentication can not authenticate in moodle, giving user error and password , so I noticed there is no moodle interaction with office365 multifactor authentication.
Our goal is for users who opt for Multi Factor Authentication to log in to moodle.

**Comment by jamesmcq** [comment]
Are you using a third-party plugin for multi-factor authentication like https://moodle.org/plugins/auth_a2fa?

**Comment by pedroalpacheco** [comment]
I am not using Two-factor authentication method https://moodle.org/plugins/auth_a2fa, because our authentication is done with active directory via azure in office365.

**Comment by pedroalpacheco** [comment]
Authentication of two-factors is done in the portal www.office.com, the user enables authentication.

**Comment by jamesmcq** [comment]
Okay, so you're doing the multi-factor on the Office side? So the user enters the code on the Office login page? Which site is giving you the error? Office or Moodle?

**Comment by pedroalpacheco** [comment]
This error in moodle, when the user did not enable the two-factors it normally connects in moodle, when the user enables in the site www.office.com two-factors can not log in to MOODLE, it presents user error and password, reason why I can see, moodle through the authentication plugin does not stop asking the office365 for a two-factor request.

**Comment by chris-let** [comment]
Hi all
I'm also getting this error - happy to share more details directly if anyone is working on this.
Thanks in advance.

**Comment by jamesmcq** [comment]
@pedroalpacheco @chris-let Interested to hear more, can you describe the issue (specific errors, etc), and the steps leading up to it? What should happen is Moodle redirects the user to Office 365, all login actions happen on the Office site, including multi-factor auth, then once everything is authenticated, Office redirects the user back to Moodle with the authorization token. @pedroalpacheco it sounds like your saying Moodle redirects the user back to Office 365 multiple times?

**Comment by chris-let** [comment]
Thanks @jamesmcq - we are using the 'Resource Owner Password Credentials Grant' method, which handles the authentication on the Moodle login page, not the Office 365 site, as with 'Authorization Code Flow'. I am aware of the potential security issues with this method, but this isn't an issue for my setup. There is no problem for the vast majority of our users - we just have a small number of 'head office' users with MFA enabled and these have the issue. My workaround is to use LDAP for these users, but I'd prefer to have all using OIDC.

Here is the full error we get, for your reference:

`oidcclient::rocredsrequest: Error in rocredsrequest request Data: (string)Error in OpenID Connect: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000002-0000-0000-c000-000000000000'. Trace ID: XXXX Correlation ID: XXXXX Timestamp: 2018-08-17 09:23:12Z
 
auth_oidc\oidcclient::rocredsrequest:224: Error response received. Data: Array ( [error] => interaction_required [error_description] => AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000002-0000-0000-c000-000000000000'. Trace ID: XXXXXX Correlation ID: XXXXXX Timestamp: 2018-08-17 09:23:12Z [error_codes] => Array ( [0] => 50076 ) [timestamp] => 2018-08-17 09:23:12Z [trace_id] => XXXXXXX [correlation_id] => XXXXXXXX [suberror] => basic_action )
`

Any thoughts on this?

Thanks for your help.

**Comment by jamesmcq** [comment]
@chris-let Ah, yes this makes sense then. It looks like resource owner password credentials method will not work with MFA, as Moodle has no interface to provide the one-time-password to Office 365. Unfortunately there's nothing we can do in the plugins to support that other than point to the "Authorization Code" method, which as you mentioned, does all the authentication on the Office 365 site, including MFA.
