### ISSUE TITLE
Restrict users by group in Sync and Auth

### ISSUE THREAD

**Issue by slewislcm** [microsoft/o365-moodle#2452]
Hi,

Not sure where else to ask this, but I can't figure out how to restrict the sync and authentication by Azure groups.
In the Microsoft 365 Integration plugin, the sync creates everyone on the AD, and when I've tried restrict it, it creates no-one. I want to restrict create users by a security group.

So in the field  local_o365 | usersynccreationrestriction I tried : 
Object ID : fgfgfgfgf-0486-461a-hjhjhh-d37316e454545 (object ID of a security group) - didn't create user
Microsoft 365 Group Membership : eg 'Students' (group name) - didn't create user
Microsoft 365 Group Membership : eg fgfgfgf-0486-461a-klklkl-d37316e454545 (object ID of a security group) - didn't create user

So am I missing something? Where else would I put in the group name or object ID.

Also in the auth oidc, can I restrict that by group (or multiple groups)? 
Would that be in the auth_oidc | userrestrictions box? 

thanks,
Simon

**Comment by weilai-irl** [comment]
Hi @slewislcm 

The current "Microsoft 365 Group Membership" option for the "User creation restriction" setting works on group names, rather than group object ID. There is a feature request (#2485, created after this issue was reported) to extend this to group object ID, but the request hasn't been implemented yet. The feature expects Microsoft 365 group name to be exact match of the settings to work.

It's no possible to supply multiple values in setting. If you want to be able to create users from multiple groups, the recommended way is to use [dynamic groups](https://learn.microsoft.com/en-us/entra/identity/users/groups-create-rule).

Hope this helps.

Regards,
Lai

**Comment by slewislcm** [comment]
Thanks. I managed to get it working in the end.
I thought I could get it to restrict by group at the auth/login stage, but it just seems to be in the create users sync. But I think that's fine for us.
Useful for to know about the dynamic groups.
thanks,
Simon

**Comment by slewislcm** [comment]
Figured it out and working correctly. thanks
