### ISSUE TITLE
Matching existing users with OIDC auth does not work

### ISSUE THREAD

**Issue by upats** [Microsoft/o365-moodle#252]
I have the Azure AD sync settings set so that preexisting Moodle accounts should be matched with Azure AD accounts.

According to the help bubble, it says the username bob.smith in Moodle would match the Azure AD username bob.smith@example.com. 

Instead what's happening is a new user is being created with username bob.smith@example.com within Moodle.

This happens whether the user is created via scheduled tasks or through the login flow.

I'm on Moodle 3.4.3+ and the latest Moodle 3.4 stable branches of the o365 plugins.

**Comment by chriskincaid24** [comment]
We are having what seems like the same issue. running moodle 3.2 and 3.2.0.2 of the oidc plugin, 3.2.0.4 of the office365 plugin.   Our user accounts are created by integration app from our SIS (Colleague with ILP) and matched to o365 by uploading a CSV.  We turned on the Moodle option 'Prevent account creation when authenticating' recently, so we do not get the duplicate accounts any longer.  When we troubleshoot, it seems there is an attempt to automatically match, there is an record in the mdl_auth_oidc showing a token issued to the UPN of the user.  Our moodle accounts are the sAMAccountName of the user (no @domain). To resolve, we have to go into the mdl_auth_oidc_token table, find the o365 name, and delete the row, and re run the matching process.

**Comment by chriskincaid24** [comment]
We realized what was happening, and created a workflow change to avoid this issue.  Students sometimes get their new account information before their accounts in Moodle get provisioned.

**Comment by fellowapeman** [comment]
@chriskincaid24 

So you mean to say by selecting Moodle's "Prevent account creation with authenticating" option fixes the issue?

There is the local o365 Sync setting "Create accounts in Moodle for users in Azure AD" which I would then need to enable--we don't do manual user uploads so we need some way to have accounts auto-created upon login or via scheduled task. I would hope that enabling this would override Moodle's "prevent" option.

**Comment by chriskincaid24** [comment]
For us, checking 'prevent account creation' partially fixed the duplicate
account issues.  We no longer have issues with duplicated accounts, but we
have an issue with, is when users attempt to log in WITHOUT a moodle
account, they still get an authentication token. SO when we bulk load our
users, and then run the user matching tool, the matching tool sees the auth
token, and thinks the user already has a moodle account, and does not match
them, so our users can't login.

**Comment by cb526** [comment]
> For us, checking 'prevent account creation' partially fixed the duplicate
account issues.  We no longer have issues with duplicated accounts, but we
have an issue with, is when users attempt to log in WITHOUT a moodle
account, they still get an authentication token. SO when we bulk load our
users, and then run the user matching tool, the matching tool sees the auth
token, and thinks the user already has a moodle account, and does not match
them, so our users can't login.

This isn't workable for a large school at all.

**Comment by jamesmcq** [comment]
Hi All - it looks like we have two different things going on here.

@upats To confirm what you're seeing, is this correct? You have an account in Moodle - "bob.smith", and have the "Match preexisting Moodle users with same-named accounts in Azure AD" setting enabled. When the sync process runs, you're seeing a new account created with the username "bob.smith@example.com", instead of matching with the existing account? If this is accurate a few questions and some possibilities:
- Do you have "Create accounts in Moodle for users in Azure AD" enabled as well? If so, this may be conflicting with the "Match preexisting Moodle users" setting. Is your workflow something along the lines of "Match with an existing user if they exist, otherwise create them"?
- If the "Create accounts in Moodle for users in Azure AD" is NOT enabled, are the users getting created when they log in? If so, this is similar to what the rest of the comments here seem to be about...

@chriskincaid24 @fellowapeman @cb526 It seems the issues you're describing are due to the number of ways a user can be created in Moodle from an Azure AD user. A user can be created during the sync process, which is what it seems you want to happen, or by logging in to Moodle using Azure AD before an account is created in Moodle, assuming the "prevent account creation" setting referred to is disabled. If, as mentioned, users sometimes get Azure AD credentials before their Moodle account is created, and you don't want them to be able to log in until their Moodle account is created, disabling the "Prevent account creation" setting is the way to accomplish this. It was also mentioned that you'd hoped the "Create accounts in Moodle for users in Azure AD" sync setting would override the "Prevent account creation" setting - these do not impact each other and each control different ways for a user to be created. This was a choice made to respect core Moodle settings as much as possible, but I'm interested to hear any additional thoughts.

@cb526 you mentioned the "prevent account creation" setting is not workable for a large school - can you expand on why that is and what would work for you?

**Comment by jamesmcq** [comment]
Hi all - I'm going to close this issue for now as the above comment should address what's going on here. If you continue to experience issues or have any other questions feel free to continue the conversation or start a new issue. Thanks!

**Comment by cb526** [comment]
Seeing as this feature still doesn't work, should it just be removed from the Moodle UI if it's not going to be fixed?
