### ISSUE TITLE
Error in delta: UserSync

### ISSUE THREAD

**Issue by robduncan1** [Microsoft/o365-moodle#258]
Moodle 3.4.4 with latest o365 Plugin.
"release":"3.4.4+ (Build: 20180727)","version":"2017111304.04","localo365forcelegacyapi":1},"plugin_data":{"auth_oidc":{"version":"2017111301","enabled":1,"

I am using the legacy API and have placed that setting in config.php 
While trying to use the graph API I received the errors and symptoms detailed in this issue:
https://github.com/Microsoft/o365-moodle/issues/215
(it's closed but users keep commenting so probably needs to be reopened)

While trying to run the sync task I get the following:

Execute scheduled task: Sync users with Azure AD. (local_o365\task\usersync)
...... Starting sync
...... No skiptoken (delta) stored.
...... No deltatoken stored.
...... Using delta sync.
...... Contacting Azure AD...
...... Error in delta usersync: Error in API call: Invalid property: telephoneNumber
...... Resetting skip and delta tokens.
...... Got response from Azure AD
...... Clearing deltatoken (none received)
...... Clearing skiptoken (delta) (none received)
...... No users received to sync.
...... Sync process finished.
... used 11 dbqueries
... used 0.34850978851318 seconds
Scheduled task complete: Sync users with Azure AD. (local_o365\task\usersync)

from the recorded debug message:
usersync task: Error in API call: Invalid property: telephoneNumber Data: Array ( [file] => /var/www/html/moodle/local/o365/classes/rest/o365api.php [line] => 284 [message] => Error in API call: Invalid property: telephoneNumber [debuginfo] => [errorcode] => erroro365apibadcall_message [module] => local_o365 ) 

This just started happening randomly, all of the config settings were successfully syncing users yesterday.

I am not mapping telephoneNumber, the default mapping has not been altered. but,
I have tried adding telephone number to the mapping and mapping it to Moodle 'mobile' field but this does not change anything.

#######
Also when a user attempts to log in who has not yet been synced from Azure AD I'm getting the following error:

API failure | local_o365\observer::handle_user_enrolment_created: Not configured Data: (null)

I am not using any of the sharepoint, school data sync, preview, or group features, so this is strange behavior also.

**Comment by robduncan1** [comment]
If we enable 'full sync' within the sync options then the scheduled task can be run again, but a full sync for us takes several hours.

Other observations, the version number for this release seems to be wrong.

Microsoft Office 365 Integrationlocal_o365 | 3.4.0.3  2017111303

**Comment by wolfstettler** [comment]
We are experiencing the same errors.
Moodle version: Moodle 3.4.5 (Build: 20180910)
local_o365 version: 2017111303
local_office365 version: 2017111300
auth_oidc version: 2017111301
block_microsoft version: 2017111301

The error we get is:
Execute scheduled task: Synchronisieren Sie Benutzer mit Azure AD. (local_o365\task\usersync)
... started 08:40:50. Current memory use 9.8MB.
...... Starting sync
...... No skiptoken (delta) stored.
...... No deltatoken stored.
...... Using delta sync.
...... Contacting Azure AD...
...... Error in delta usersync: Fehler bei API-Aufruf: Invalid property: telephoneNumber
...... Resetting skip and delta tokens.
...... Got response from Azure AD
...... Clearing deltatoken (none received)
...... Clearing skiptoken (delta) (none received)
...... No users received to sync.
...... Sync process finished.
... used 4 dbqueries
... used 0.82694482803345 seconds
Scheduled task complete: Synchronisieren Sie Benutzer mit Azure AD. (local_o365\task\usersync)

This issue is a blocker for us, because we are not able to sync the users Azure with those in Moodle.

**Comment by limsko** [comment]
**Workaround:** Comment theese three lines:
`            //'telephoneNumber',`
`            //'facsimileTelephoneNumber',`
`            //'mobile',`
in function get_default_user_fields() in file: /local/o365/classes/rest/unified.php

**Comment by jamesmcq** [comment]
Hi all - it does look like these fields are no longer available. Thanks for the details logs, these will be removed in the next version.

**Comment by jamesmcq** [comment]
Hi All - a fix for this is included in the latest release. Thanks!
