### ISSUE TITLE
No language string for user restriction error

### ISSUE THREAD

**Issue by slewislcm** [microsoft/o365-moodle#2616]
Hi,
We're using the auth_oidc | userrestrictions and it would be useful if there was a an error lang string we could we could update to give clearer instructions to users.
Seems to just be a default exception string:
Exception - Class "auth_oidc\action_failed" not found

thanks,
Simon

**Comment by weilai-irl** [comment]
Hi @slewislcm 

The error in your note suggests PHP cannot file the class "auth_oidc\action_failed". It's an PHP error, rather than an Moodle error. I checked the latest release of the plugins for the supported Moodle version, and I couldn't reproduce the issue. Please upgrade to the latest versions to solve the issue.

After the issue is solved, e.g. you are not seeing the PHP class not found error, but a Moodle exception, you can then customise the string with identifier "errorrestricted" in auth_oidc plugin, which controls what the end user will see.

Regards,
Lai
