### ISSUE TITLE
One singular Admin user receives daily mail "Action required: invalid Azure app secret found" the others do not.

### ISSUE THREAD

**Issue by Denis-WUAS** [microsoft/o365-moodle#2620]
Hello, one of our admin users receives the below email every day.

_Dear site administrator,

The Azure app secret used in your Moodle and Microsoft 365 integration seems to be invalid. This can either be caused by the secret expired, or it has been deleted. 
Please review the secret to ensure the integration works as expected._

Nobody else does and the system works for everyone, including said admin.

We had that issue for a long time now and always hoped a Moodle update would resolve it. So far not.
Any attempt to clear caches, update the field that we can and re-authenticate have not helped.

Do you haven an idea where this is coming from?
Are there any pitch falls to look out for when disabling the module to apply a new app/secret to it or is there a way to update it without re-installing?

Moodle 4.4.2+
auth_oidc 4.4.0
local_o365 4.4.0
repository_office365 4.4.0
block_microsoft 4.4.0

Thank you very much,
Denis

**Comment by AntonT76** [comment]
Hi @Denis-WUAS 

we also have the same issue, but in older Moodle version (4.1.9+) and older Microsoft plugins, see details in https://github.com/microsoft/o365-moodle/issues/2334. Maybe some hints could help you. The error message currently has no negative impact on us (user synchronisation and login are working).

We will do an update of Moodle and Microsoft plugins next week and we may also try to make a completely new app registration in Azure.  Maybe we can solve the problem during the update or within the new app registration.

br, Anton

**Comment by Denis-WUAS** [comment]
Hi @AntonT76, am very curious about your findings. - Did you do the update and or the plugin reset/reinstallation? 

Greetings, Denis :)

**Comment by AntonT76** [comment]
Hello @Denis-WUAS 

a few days ago we did an upate to Moodle version 4.1.12 and the latest Microsoft plugins. We also did a new Admin Consent and checked all settings in Azure. Unfortunately, the update did not help. We have also thought about to uninstall the Microsoft plugins, reinstall them and make a new app registration in Azure. Although we continue to receive this error mail message, we can't see any restrictions (login and synchronisation are running), so we did not take this step after all.

br, Anton

**Comment by weilai-irl** [comment]
Hi @Denis-WUAS 

Let me explain the logic behind the "Notify secret expiry" feature, and hopefully this will help you finding where the issue is.

First of all, the emails are triggered by a scheduled task as part of the local_o365 plugin. The scheduled task is "Notify site admin about Azure app secret expiry" (\local_o365\task\notifysecretexpiry), and the default schedule is once daily, at 3am.

The recipient of the notification is configured in the "Secret Expiry Notification Recipients" setting of the auth_oidc plugin. The setting is on the "IdP and authentication" configuration page of the auth_oidc plugin. The setting accepts multiple email addresses, separated by comma; if no email address is provided, the main site admin will receive the notification.

When the task runs, the following happens:

- Check if the integration can call Microsoft Graph API endpoints. If it can't, the task will end without sending any notification.
- Check if the "Client authentication method" setting of the auth_oidc plugin is set to be "Secret". If it's set to any other value, the task will end without sending any notification.
- The task will try to get information about all the client secrets of the Azure app used for the integration by calling [the "List applications" API endpoint](https://learn.microsoft.com/en-us/graph/api/application-list?view=graph-rest-beta&tabs=http). Note this only returns certain attributes of the secrets, not the secrets themselves. If the Graph API call fails, notifications are sent out, and task run ends here.
- Then the task will try to find the secret used for the configuration by going through each of the secrets received, comparing the "hint" of the secret (first 3 character of the secret) with the secret stored in Moodle settings. If the secret is not found, notifications are sent out and task run ends; if the secret is found, then the task checks whether the expiry date of the secret has passed, or will pass in the next 4 weeks, and send out notifications accordingly; otherwise the task will finish running without sending out notifications.

The task log would contains more details on why notifications are sent out. Please check them too.

@AntonT76 FYI, just in case it help you troubleshooting the issue you mentioned.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @Denis-WUAS

To answer this part of your question:

> Are there any pitch falls to look out for when disabling the module to apply a new app/secret to it or is there a way to update it without re-installing?

There are what happens:

- If you just change the secret, nothing will be changed. If the previous secret has expired, or was expiring, then after the change will you will stop receiving the notification you mentioned.
- If you change the authentication method, e.g. from secret to certificate, the stored application tokens, admin consent status, as well as verify setup outcomes will be deleted. Azure admins will need to provide admin consent from the local_o365 configuration page again. This will create a new application token that the plugins can use to call Microsoft Graph API calls. If they don't do that, the plugins will have no access to Microsoft data (besides user ID and access tokens from login).
- If you change the application ID, even to a different application from the same tenant, then besides the data mentioned in the previous point, a lot more records will be deleted. This includes:  
  - Stored auth_oidc user token (in mdl_auth_oidc_token table).
  - All Moodle and Microsoft user connection records (stored in mdl_local_o365_objects table).
  - If delta sync is used in the the user sync task, then the stored delta token will be deleted too.

Hope this helps.

Regards,
Lai
