### ISSUE TITLE
best way to uninstall

### ISSUE THREAD

**Issue by thomasjsweet** [microsoft/o365-moodle#2628]
Hello, we need to remove the m365 support for business reasons, nothing related to features or quality.

I shut the "eye" off for openid and deleted the app registration in azure.  M365 is gone and the site still works - that is good.

What is the best way to remove the plugins - I have 
openid connect
microsoft 365 integration x 2  (/local0365 and /local/office365)
Microsoft block

maybe some others.  The goal is no errors related to plug-ins when I upgrade moodle.

thx

**Comment by weilai-irl** [comment]
Hi @thomasjsweet 

This is an interesting question.

In general, you can uninstall Moodle plugins by going to the plugins overview page (https://url.to.moodle/admin/plugins.php), click the "Uninstall" button against a plugin to install it. It will delete all the database tables defined by the plugin, and remove associated data if there's any. Note you will need to confirm deletion, and remove the actual code from your dirroot before going back to the "Plugins check" page, otherwise the plugin will be re-installed, since the code still exists.

With this in mind, you will need to delete all the plugins in the Microsoft suite one by one, but there is a twist here - there are dependencies between some plugins, so they have to be uninstalled in a certain order. Please follow this order for the cleanest results:

1. local_office365.
2. assignfeedback_onenote
3. assignsubmission_onenote
4. theme_boost_o365teams
5. repository_office365
6. block_microsoft
7. local_onenote
8. local_o365
9. auth_oidc, note in order to uninstall auth_oidc, you will need to make sure that there are not remaining Moodle accounts using the authentication method - they need to be migrated to other authentication method beforehand.

Hope it helps.

Regards,
Lai

**Comment by thomasjsweet** [comment]
Thank you - I am going to try this over the weekend.

**Comment by thomasjsweet** [comment]
I got through all of them but could not remove the auth_oidc.   Despite having no users with that auth, I never saw the uninstall.
