### ISSUE TITLE
auth_oidc incorrectly updating the email field to username on logon only

### ISSUE THREAD

**Issue by slewislcm** [microsoft/o365-moodle#2672]
Hi,
I've tested this on version 4.1.6 & 4.1.7. When a user login in with 365 it is updating their email on moodle to their 365 username, even when it's set to email. And most of ours usernames have different emails to their username.
Strangely the local_365 user sync works correctly, so basically it corrects it when the sync runs overnight, then incorrectly updates it when they next login (was confusing me for ages!)

Data mapping (Email address) is mapped to 'email'. 
auth_oidc | field_updatelocal_email is set to all 3 create/login/sync. If the option of just 'sync' was there I'd choose that, but as a workaround I've set to option 'on creation' only.

Any ideas? I've checked everything, and can't anywhere else where it would be badly set up.
Moodle 4.1.11 fyi

thanks,
Simon

**Comment by AntonT76** [comment]
Hi @slewislcm 

it seems to be that this is the same issue like https://github.com/microsoft/o365-moodle/issues/2268#issuecomment-2265606306
You can find the solution at the end of the issue.

br, Anton

**Comment by weilai-irl** [comment]
Hi @slewislcm 

@AntonT76 pointed you to the right direction. The easiest solution is to add "email" as an optional claim to either ID token or access token. For a bit of more background, please read on.

When processing field mapping on user login, there are two ways the integration can get remote user profile - from token claims, or via Graph API calls. The decision of which way to use depends on the remote fields configured in feature mapping - if only the very basic fields are used, i.e. ObjectID, Username (UPN), Given Name, Surname, and Email, then token claims are used; if it uses any other fields that are normally not included in the token, a Graph API call is used. The purpose of this logic is to reduce the number of Graph API calls on sites with large number of users trying to login at relatively short time, which would create large number of Graph API calls, triggering throttling.

The problem is "email" is not of the the default token claims in some cases, so when using token claims as source of remote profile, it would fall back to username (UPN) if email claim doesn't present, or if it's empty.

This isn't a problem for the user sync task, because the user sync task always uses Graph API calls to get user profile, and the call contains parameters to ensure emails are always returned.

With that understanding, another relatively easy solution besides the token claim change mentioned at the start of the note is to use additional remote fields in the field mapping settings to force syncing user profiles from Graph API calls rather than token claims on user login.

Regards,
Lai

**Comment by slewislcm** [comment]
Many thanks. Yes that's fixed it
