### ISSUE TITLE
Fallback to token claim 'sub' in handleauthresponse()

### ISSUE THREAD

**Issue by christianabila** [microsoft/o365-moodle#2680]
handlelogin() falls back to the token claim 'sub' if 'upn' and 'unique_name' are empty - I think this should happen in handleauthresponse() too.

**Comment by weilai-irl** [comment]
Hi @christianabila 

Thank you for your contribution - what you contributed makes sense.

However, there are some changes in the upcoming release of the plugins in the next few days to allow Moodle site admins to configure the binding username claim to be used as Moodle usernames (so it doesn't have to be UPN), and as part of the changes, the function get the binding username token claim is completely rewritten. I confirm the new implementation has logic to fallback to "sub" claim if everything else fails.

I'll leave this issue open until after the release, and link the code containing the new logic in to. I'll close the linked PR since it will not apply.

Thank you very much again for your contribution.

Regards,
Lai

**Comment by christianabila** [comment]
That sounds like a great new feature coming up. I can report that we stumbled over this on an OIDC setup with an IdP other than Entra ID. If we had the upcoming option, we would have had finished the setup sooner :)

**Comment by weilai-irl** [comment]
Hi @christianabila 

The feature mentioned in my last comment has been released. Please check it out.

Regards,
Lai

**Comment by christianabila** [comment]
> Hi [@christianabila](https://github.com/christianabila)
> 
> The feature mentioned in my last comment has been released. Please check it out.
> 
> Regards, Lai

Hi @weilai-irl 

Thanks for the notice. I haven't been able to find the feature in auth_oidc's admin settings pages. Are instructions available that can point me there?

Regards,
Chris

**Comment by christianabila** [comment]
> > Hi [@christianabila](https://github.com/christianabila)
> > The feature mentioned in my last comment has been released. Please check it out.
> > Regards, Lai
> 
> Hi [@weilai-irl](https://github.com/weilai-irl)
> 
> Thanks for the notice. I haven't been able to find the feature in auth_oidc's admin settings pages. Are instructions available that can point me there?
> 
> Regards, Chris

Nevermind, I have found it. idptype has to be set to be able to see the links to the settings' page. My wrong was, I tested the new plugin version on a Moodle installation with no fully setup auth_oidc. Closing this issue.
