### ISSUE TITLE
Moodle notifications not getting pushed to Teams

### ISSUE THREAD

**Issue by bebo553** [microsoft/o365-moodle#2690]
Moodle notifications not getting pushed to Teams notifications

**Comment by weilai-irl** [comment]
Hi @bebo553 

I can confirm that this isn't a feature supported by the Moodle and Teams integration.

Previously there was a Teams bot feature in the integration that pushes Moodle integration to Teams, but this feature has been deprecated because the underlying technology that the feature was built on was retired. There is no plan to add the notification integration feature back at the moment.

Regards,
Lai
