### ISSUE TITLE
Setting system API returns error

### ISSUE THREAD

**Issue by envycreative** [Microsoft/o365-moodle#50]
When setting the system API user in the settings our moodle site is returning the error: 
OIDC id_token not received after user login at login.micosoftonline.com.

I've looked around to see if anyone else is having this error, but cant find the same problem, issue 43 seems to have similar resemblances to the issue maybe?

Any ideas as to what may be causing this?

**Comment by jamesmcq** [comment]
Hi envycreative,

Have you set up the OpenID Connect authentication plugin? (Client ID and secret, correct Azure permissions?) Are you noticing any other functionality problems?

**Comment by envycreative** [comment]
Yep,

OpenID is setup correctly. On the office 365 plugin setup page I have green on the following:

Application Credentials
Azure AD Tenant
OneDrive for Business URL
and Moodle is busy making a SharePoint site (but it has been for a week, im assuming this is due to it not having an API user set).

Application permissions is set as Red, yet all permissions are set up in Azure AD correctly...

When I Click Set API user, and put the relevant details in, it goes back to http://domain.com/auth/oidc/ with a the above error.

Steve

**Comment by alight-eskillz** [comment]
I'm getting the same issue here.  I've successfully set up everything except that the Windows Azure Active Directory | UserProfile.Read permission keeps showing up in Moodle as not applied, even though I've applied it.  Maybe that's why the SharePoint site isn't created...

Here are the permissions I've applied in Azure AD (more than what you've indicated in the documentation, as I've been trying to get it to work:

# oauth 2.0 permission grants

## OFFICE 365 EXCHANGE ONLINE
Read and write user calendarsHelp
Read user calendarsHelp

## OFFICE 365 SHAREPOINT ONLINE
Have full control of all site collectionsHelp
Read and write items and lists in all site collectionsHelp
Read and write items in all site collectionsHelp
Read and write user filesHelp
Read items in all site collectionsHelp
Read user filesHelp

## ONENOTE
Create pages in OneNote notebooksHelp
View and modify OneNote notebooksHelp
View OneNote notebooksHelp

## WINDOWS AZURE ACTIVE DIRECTORY
Access the directory as the signed-in userHelp
Read all users' basic profilesHelp
Read all users' full profilesHelp
Read directory dataHelp
Sign in and read user profileHelp

I also get a JavaScript error after clicking the Update button in the plugin's Application Permissions section (seems to be a coding issue), which you can see in this image:

![missingunifiedperms](https://cloud.githubusercontent.com/assets/11045770/10381302/d15ff954-6dd6-11e5-82dc-f10e94616ee1.png)

I'm really looking forward to getting the O365 plugins to work as intended.  Thanks.

**Comment by jamesmcq** [comment]
The UserProfile.Read message isn't the cause here - Azure updated it's permission names and the permissions checker needs an update to check for the new name. API calls still work so it wouldn't affect SharePoint functionality, the issue is limited to the permissions checker tool.

**Comment by envycreative** [comment]
Any further news on what could be causing this issue. One other thought. We have O365 SSO setup on the azure side to redirect all "@domain.com" accounts so when I get the login.microsoft.com page, put in an admin account it redirects to https://sso.domain.com/adfs/ls/?variable_etc   

Would this be part of the issue. Even when I use one of our admin accounts sso@domain.onmicrosft.com it still returns oidc error... could do with a solution asap so we can start building our new moodle instance.

**Comment by jamesmcq** [comment]
Hi Envycreative,

The latest release of OpenID Connect includes debug logging, which should pinpoint the exact reason you're getting OIDC id_token not received. If you go to the OpenID Connect settings page, you'll see a "Record debug messages" setting. If you enable this, and try setting the system API user again, you should get a debug message in the Moodle log. This log can be viewed at Site Administration > Reports > Logs. Change the "All activities" select box to "Site Errors" and click "get these logs". You should see a log entry for "OpenID Connect" with the event name "Debug message". Please email me the information in this event at james.mcquillan@remote-learner.net and I can further help solve the issue. Don't post the information here as it may contain sensitive information.
